// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daemonset.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DaemonSetService struct {
	ProjectId            string                      `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId            string                      `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name                 string                      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version              string                      `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	ServiceType          string                      `protobuf:"bytes,5,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ServiceSubType       string                      `protobuf:"bytes,6,opt,name=service_sub_type,json=serviceSubType,proto3" json:"service_sub_type,omitempty"`
	Namespace            string                      `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Token                string                      `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	CompanyId            string                      `protobuf:"bytes,9,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ServiceAttributes    *DaemonSetServiceAttributes `protobuf:"bytes,10,opt,name=service_attributes,json=serviceAttributes,proto3" json:"service_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DaemonSetService) Reset()         { *m = DaemonSetService{} }
func (m *DaemonSetService) String() string { return proto.CompactTextString(m) }
func (*DaemonSetService) ProtoMessage()    {}
func (*DaemonSetService) Descriptor() ([]byte, []int) {
	return fileDescriptor_6841f345540e0841, []int{0}
}

func (m *DaemonSetService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DaemonSetService.Unmarshal(m, b)
}
func (m *DaemonSetService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DaemonSetService.Marshal(b, m, deterministic)
}
func (m *DaemonSetService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DaemonSetService.Merge(m, src)
}
func (m *DaemonSetService) XXX_Size() int {
	return xxx_messageInfo_DaemonSetService.Size(m)
}
func (m *DaemonSetService) XXX_DiscardUnknown() {
	xxx_messageInfo_DaemonSetService.DiscardUnknown(m)
}

var xxx_messageInfo_DaemonSetService proto.InternalMessageInfo

func (m *DaemonSetService) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *DaemonSetService) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *DaemonSetService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DaemonSetService) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DaemonSetService) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *DaemonSetService) GetServiceSubType() string {
	if m != nil {
		return m.ServiceSubType
	}
	return ""
}

func (m *DaemonSetService) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DaemonSetService) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DaemonSetService) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *DaemonSetService) GetServiceAttributes() *DaemonSetServiceAttributes {
	if m != nil {
		return m.ServiceAttributes
	}
	return nil
}

type DaemonSetServiceAttributes struct {
	Labels               map[string]string               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations          map[string]string               `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LabelSelector        *LabelSelectorObj               `protobuf:"bytes,3,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	UpdateStrategy       *DaemonSetUpdateStrategy        `protobuf:"bytes,4,opt,name=updateStrategy,proto3" json:"updateStrategy,omitempty"`
	MinReadySeconds      int32                           `protobuf:"varint,7,opt,name=minReadySeconds,proto3" json:"minReadySeconds,omitempty"`
	RevisionHistoryLimit *RevisionHistoryLimit           `protobuf:"bytes,8,opt,name=revisionHistoryLimit,proto3" json:"revisionHistoryLimit,omitempty"`
	Affinity             *Affinity                       `protobuf:"bytes,5,opt,name=affinity,proto3" json:"affinity,omitempty"`
	Volumes              []*Volume                       `protobuf:"bytes,9,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Containers           map[string]*ContainerAttributes `protobuf:"bytes,10,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	InitContainers       map[string]*ContainerAttributes `protobuf:"bytes,11,rep,name=initContainers,proto3" json:"initContainers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NodeSelector         map[string]string               `protobuf:"bytes,6,rep,name=node_selector,json=nodeSelector,proto3" json:"node_selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IstioConfig          *IstioConfig                    `protobuf:"bytes,12,opt,name=istio_config,json=istioConfig,proto3" json:"istio_config,omitempty"`
	IsRbacEnabled        bool                            `protobuf:"varint,19,opt,name=is_rbac_enabled,json=isRbacEnabled,proto3" json:"is_rbac_enabled,omitempty"`
	Roles                []*K8SRbacAttribute             `protobuf:"bytes,20,rep,name=roles,proto3" json:"roles,omitempty"`
	IstioRoles           []*IstioRbacAttribute           `protobuf:"bytes,21,rep,name=istio_roles,json=istioRoles,proto3" json:"istio_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *DaemonSetServiceAttributes) Reset()         { *m = DaemonSetServiceAttributes{} }
func (m *DaemonSetServiceAttributes) String() string { return proto.CompactTextString(m) }
func (*DaemonSetServiceAttributes) ProtoMessage()    {}
func (*DaemonSetServiceAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6841f345540e0841, []int{1}
}

func (m *DaemonSetServiceAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DaemonSetServiceAttributes.Unmarshal(m, b)
}
func (m *DaemonSetServiceAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DaemonSetServiceAttributes.Marshal(b, m, deterministic)
}
func (m *DaemonSetServiceAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DaemonSetServiceAttributes.Merge(m, src)
}
func (m *DaemonSetServiceAttributes) XXX_Size() int {
	return xxx_messageInfo_DaemonSetServiceAttributes.Size(m)
}
func (m *DaemonSetServiceAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_DaemonSetServiceAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_DaemonSetServiceAttributes proto.InternalMessageInfo

func (m *DaemonSetServiceAttributes) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetLabelSelector() *LabelSelectorObj {
	if m != nil {
		return m.LabelSelector
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetUpdateStrategy() *DaemonSetUpdateStrategy {
	if m != nil {
		return m.UpdateStrategy
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetMinReadySeconds() int32 {
	if m != nil {
		return m.MinReadySeconds
	}
	return 0
}

func (m *DaemonSetServiceAttributes) GetRevisionHistoryLimit() *RevisionHistoryLimit {
	if m != nil {
		return m.RevisionHistoryLimit
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetAffinity() *Affinity {
	if m != nil {
		return m.Affinity
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetContainers() map[string]*ContainerAttributes {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetInitContainers() map[string]*ContainerAttributes {
	if m != nil {
		return m.InitContainers
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetNodeSelector() map[string]string {
	if m != nil {
		return m.NodeSelector
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetIstioConfig() *IstioConfig {
	if m != nil {
		return m.IstioConfig
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetIsRbacEnabled() bool {
	if m != nil {
		return m.IsRbacEnabled
	}
	return false
}

func (m *DaemonSetServiceAttributes) GetRoles() []*K8SRbacAttribute {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *DaemonSetServiceAttributes) GetIstioRoles() []*IstioRbacAttribute {
	if m != nil {
		return m.IstioRoles
	}
	return nil
}

func init() {
	proto.RegisterType((*DaemonSetService)(nil), "proto.DaemonSetService")
	proto.RegisterType((*DaemonSetServiceAttributes)(nil), "proto.DaemonSetServiceAttributes")
	proto.RegisterMapType((map[string]string)(nil), "proto.DaemonSetServiceAttributes.AnnotationsEntry")
	proto.RegisterMapType((map[string]*ContainerAttributes)(nil), "proto.DaemonSetServiceAttributes.ContainersEntry")
	proto.RegisterMapType((map[string]*ContainerAttributes)(nil), "proto.DaemonSetServiceAttributes.InitContainersEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.DaemonSetServiceAttributes.LabelsEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.DaemonSetServiceAttributes.NodeSelectorEntry")
}

func init() { proto.RegisterFile("daemonset.proto", fileDescriptor_6841f345540e0841) }

var fileDescriptor_6841f345540e0841 = []byte{
	// 793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0x1b, 0x45,
	0x14, 0xc5, 0x4e, 0x9d, 0xc4, 0x77, 0xfd, 0x91, 0x4e, 0x03, 0x5d, 0xcc, 0x87, 0xd2, 0x3c, 0x80,
	0x25, 0xd4, 0x08, 0xb6, 0xaa, 0x54, 0xfa, 0x50, 0x14, 0x39, 0x01, 0x2c, 0x2a, 0x1a, 0xc6, 0x05,
	0xc1, 0x43, 0x65, 0xcd, 0xee, 0xde, 0x84, 0x69, 0xd7, 0x33, 0xab, 0x9d, 0xb1, 0xa5, 0xfd, 0xb3,
	0x3c, 0xf0, 0x0b, 0xf8, 0x09, 0x68, 0x3e, 0x6c, 0x6f, 0x16, 0x57, 0x56, 0x64, 0x9e, 0xbc, 0xf7,
	0xdc, 0x73, 0xce, 0xdc, 0xd9, 0x39, 0x3b, 0x86, 0x7e, 0xca, 0x70, 0x26, 0x85, 0x42, 0x7d, 0x96,
	0x17, 0x52, 0x4b, 0xd2, 0xb2, 0x3f, 0x83, 0xee, 0x0d, 0x0a, 0x2c, 0x58, 0x76, 0xe6, 0x4b, 0x85,
	0xc5, 0x82, 0x27, 0xe8, 0xcb, 0xce, 0x42, 0x66, 0xf3, 0x99, 0xaf, 0x4e, 0xff, 0x69, 0xc2, 0xd1,
	0x85, 0xb5, 0x99, 0xa0, 0x9e, 0x38, 0x22, 0xf9, 0x0c, 0x20, 0x2f, 0xe4, 0x5b, 0x4c, 0xf4, 0x94,
	0xa7, 0x61, 0xe3, 0xa4, 0x31, 0x6c, 0xd3, 0xb6, 0x47, 0xc6, 0xa9, 0x69, 0x7b, 0x4b, 0xd3, 0x6e,
	0xba, 0xb6, 0x47, 0xc6, 0x29, 0x21, 0x70, 0x4f, 0xb0, 0x19, 0x86, 0x7b, 0xb6, 0x61, 0x9f, 0x49,
	0x08, 0x07, 0x0b, 0x2c, 0x14, 0x97, 0x22, 0xbc, 0x67, 0xe1, 0x65, 0x49, 0x1e, 0x41, 0x67, 0x69,
	0xa6, 0xcb, 0x1c, 0xc3, 0x96, 0x6d, 0x07, 0x1e, 0x7b, 0x5d, 0xe6, 0x48, 0x86, 0x70, 0xb4, 0xa4,
	0xa8, 0x79, 0xec, 0x68, 0xfb, 0x96, 0xd6, 0xf3, 0xf8, 0x64, 0x1e, 0x5b, 0xe6, 0xa7, 0xd0, 0x36,
	0xcb, 0xa9, 0x9c, 0x25, 0x18, 0x1e, 0xb8, 0xc1, 0x56, 0x00, 0x39, 0x86, 0x96, 0x96, 0xef, 0x50,
	0x84, 0x87, 0xb6, 0xe3, 0x0a, 0xb3, 0x9b, 0x44, 0xce, 0x72, 0x26, 0x4a, 0xb3, 0x9b, 0xb6, 0x13,
	0x79, 0x64, 0x9c, 0x92, 0x2b, 0x20, 0xcb, 0xc5, 0x99, 0xd6, 0x05, 0x8f, 0xe7, 0x1a, 0x55, 0x08,
	0x27, 0x8d, 0x61, 0x10, 0x3d, 0x72, 0x2f, 0xf1, 0xac, 0xfe, 0x02, 0xcf, 0x57, 0x44, 0x7a, 0x5f,
	0xd5, 0xa1, 0xd3, 0xbf, 0x00, 0x06, 0xef, 0x57, 0x90, 0x4b, 0xd8, 0xcf, 0x58, 0x8c, 0x99, 0x0a,
	0x1b, 0x27, 0x7b, 0xc3, 0x20, 0x7a, 0xbc, 0x75, 0x91, 0xb3, 0x97, 0x96, 0x7f, 0x29, 0x74, 0x51,
	0x52, 0x2f, 0x26, 0xaf, 0x21, 0x60, 0x42, 0x48, 0xcd, 0x34, 0x97, 0x42, 0x85, 0x4d, 0xeb, 0x15,
	0x6d, 0xf7, 0x3a, 0x5f, 0x8b, 0x9c, 0x61, 0xd5, 0x86, 0xbc, 0x80, 0x9e, 0xf5, 0x9f, 0x2a, 0xcc,
	0x30, 0xd1, 0xb2, 0xb0, 0xa7, 0x1c, 0x44, 0x0f, 0xbd, 0xb1, 0x9d, 0x64, 0xe2, 0x7b, 0xaf, 0xe2,
	0xb7, 0xb4, 0x9b, 0x55, 0x11, 0xf2, 0x3d, 0xf4, 0xe6, 0x79, 0xca, 0x34, 0x4e, 0x74, 0xc1, 0x34,
	0xde, 0x94, 0x36, 0x0e, 0x41, 0xf4, 0x79, 0x7d, 0xb0, 0x5f, 0x6f, 0xb1, 0x68, 0x4d, 0x45, 0x86,
	0xd0, 0x9f, 0x71, 0x41, 0x91, 0xa5, 0xe5, 0x04, 0x13, 0x29, 0x52, 0x65, 0x8f, 0xbb, 0x45, 0xeb,
	0x30, 0x79, 0x05, 0xc7, 0x05, 0x2e, 0xb8, 0xc9, 0xda, 0x8f, 0x5c, 0x69, 0x59, 0x94, 0x2f, 0xf9,
	0x8c, 0x6b, 0x9b, 0x81, 0x20, 0xfa, 0xc4, 0xaf, 0x4b, 0x37, 0x50, 0xe8, 0x46, 0x21, 0xf9, 0x0a,
	0x0e, 0xd9, 0xf5, 0x35, 0x17, 0x5c, 0x97, 0x36, 0xac, 0x41, 0xd4, 0xf7, 0x26, 0xe7, 0x1e, 0xa6,
	0x2b, 0x02, 0xf9, 0x12, 0x0e, 0xdc, 0xe7, 0xa6, 0xc2, 0xb6, 0x3d, 0x81, 0xae, 0xe7, 0xfe, 0x66,
	0x51, 0xba, 0xec, 0x92, 0x5f, 0x4c, 0x0a, 0x85, 0x66, 0x5c, 0x60, 0x61, 0xe2, 0x65, 0xb8, 0xdf,
	0x6c, 0x3f, 0xad, 0xd1, 0x4a, 0xe3, 0x0e, 0xab, 0x62, 0x42, 0xde, 0x40, 0xcf, 0x0c, 0xb1, 0xa6,
	0x84, 0x81, 0xb5, 0x7d, 0xba, 0xdd, 0x76, 0x7c, 0x4b, 0xe7, 0xac, 0x6b, 0x66, 0xe4, 0x77, 0xe8,
	0x0a, 0x99, 0xe2, 0x3a, 0x09, 0xfb, 0xd6, 0xfd, 0xc9, 0x76, 0xf7, 0x9f, 0x65, 0x8a, 0xcb, 0x44,
	0x38, 0xef, 0x8e, 0xa8, 0x40, 0xe4, 0x29, 0x74, 0xb8, 0xd2, 0x5c, 0x4e, 0x13, 0x29, 0xae, 0xf9,
	0x4d, 0xd8, 0xb1, 0x6f, 0x99, 0x78, 0xe3, 0xb1, 0x69, 0x8d, 0x6c, 0x87, 0x06, 0x7c, 0x5d, 0x90,
	0x2f, 0xa0, 0xcf, 0xd5, 0xb4, 0x88, 0x59, 0x32, 0x45, 0xc1, 0xe2, 0x0c, 0xd3, 0xf0, 0xc1, 0x49,
	0x63, 0x78, 0x48, 0xbb, 0x5c, 0xd1, 0x98, 0x25, 0x97, 0x0e, 0x24, 0x8f, 0xa1, 0x55, 0xc8, 0x0c,
	0x55, 0x78, 0x6c, 0x07, 0x5e, 0x46, 0xf7, 0xa7, 0x67, 0x96, 0xb5, 0x9a, 0x93, 0x3a, 0x16, 0x79,
	0x0e, 0x6e, 0x95, 0xa9, 0x13, 0x7d, 0x68, 0x45, 0x1f, 0x57, 0x87, 0xb9, 0x2d, 0x03, 0xcb, 0xa6,
	0x86, 0x3c, 0xf8, 0x16, 0x82, 0xca, 0xb7, 0x49, 0x8e, 0x60, 0xef, 0x1d, 0x96, 0xfe, 0x42, 0x35,
	0x8f, 0xe6, 0x4a, 0x5a, 0xb0, 0x6c, 0x8e, 0xfe, 0x16, 0x75, 0xc5, 0xf3, 0xe6, 0xb3, 0xc6, 0xe0,
	0x05, 0x1c, 0xd5, 0x3f, 0xc5, 0x3b, 0xe9, 0xff, 0x80, 0x7e, 0xed, 0x04, 0x37, 0xc8, 0xbf, 0xae,
	0xca, 0x83, 0x68, 0xe0, 0x77, 0xb5, 0x12, 0x56, 0x2e, 0xb2, 0x8a, 0xf5, 0x1b, 0x78, 0xb0, 0x21,
	0x20, 0xff, 0x9b, 0xfd, 0x77, 0x70, 0xff, 0x3f, 0x09, 0xb9, 0xcb, 0xd6, 0xa3, 0xbf, 0x9b, 0xd0,
	0x5e, 0xc5, 0x8f, 0x5c, 0x40, 0x7f, 0x54, 0x20, 0xd3, 0xb8, 0x86, 0x1e, 0xbe, 0x27, 0xa3, 0x83,
	0x8f, 0x7c, 0xc3, 0xd7, 0x14, 0x55, 0x6e, 0xfe, 0x5f, 0x4f, 0x3f, 0x30, 0x2e, 0x17, 0x98, 0xe1,
	0x8e, 0x2e, 0xe7, 0xd0, 0xf9, 0x01, 0xf5, 0x4e, 0x16, 0x23, 0xe8, 0x5d, 0x31, 0x9d, 0xfc, 0xb9,
	0xeb, 0x1c, 0x57, 0xf3, 0x9d, 0xe6, 0x88, 0xf7, 0x6d, 0xe3, 0xc9, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x99, 0xe0, 0x38, 0x45, 0x85, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DaemonSetClient is the client API for DaemonSet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaemonSetClient interface {
	CreateDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error)
	DeleteDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error)
	GetDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error)
	PatchDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error)
	PutDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type daemonSetClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonSetClient(cc grpc.ClientConnInterface) DaemonSetClient {
	return &daemonSetClient{cc}
}

func (c *daemonSetClient) CreateDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.DaemonSet/CreateDaemonSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonSetClient) DeleteDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.DaemonSet/DeleteDaemonSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonSetClient) GetDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.DaemonSet/GetDaemonSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonSetClient) PatchDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.DaemonSet/PatchDaemonSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonSetClient) PutDaemonSet(ctx context.Context, in *DaemonSetService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.DaemonSet/PutDaemonSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonSetServer is the server API for DaemonSet service.
type DaemonSetServer interface {
	CreateDaemonSet(context.Context, *DaemonSetService) (*ServiceResponse, error)
	DeleteDaemonSet(context.Context, *DaemonSetService) (*ServiceResponse, error)
	GetDaemonSet(context.Context, *DaemonSetService) (*ServiceResponse, error)
	PatchDaemonSet(context.Context, *DaemonSetService) (*ServiceResponse, error)
	PutDaemonSet(context.Context, *DaemonSetService) (*ServiceResponse, error)
}

// UnimplementedDaemonSetServer can be embedded to have forward compatible implementations.
type UnimplementedDaemonSetServer struct {
}

func (*UnimplementedDaemonSetServer) CreateDaemonSet(ctx context.Context, req *DaemonSetService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDaemonSet not implemented")
}
func (*UnimplementedDaemonSetServer) DeleteDaemonSet(ctx context.Context, req *DaemonSetService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDaemonSet not implemented")
}
func (*UnimplementedDaemonSetServer) GetDaemonSet(ctx context.Context, req *DaemonSetService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDaemonSet not implemented")
}
func (*UnimplementedDaemonSetServer) PatchDaemonSet(ctx context.Context, req *DaemonSetService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchDaemonSet not implemented")
}
func (*UnimplementedDaemonSetServer) PutDaemonSet(ctx context.Context, req *DaemonSetService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutDaemonSet not implemented")
}

func RegisterDaemonSetServer(s *grpc.Server, srv DaemonSetServer) {
	s.RegisterService(&_DaemonSet_serviceDesc, srv)
}

func _DaemonSet_CreateDaemonSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonSetService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonSetServer).CreateDaemonSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DaemonSet/CreateDaemonSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonSetServer).CreateDaemonSet(ctx, req.(*DaemonSetService))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonSet_DeleteDaemonSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonSetService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonSetServer).DeleteDaemonSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DaemonSet/DeleteDaemonSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonSetServer).DeleteDaemonSet(ctx, req.(*DaemonSetService))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonSet_GetDaemonSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonSetService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonSetServer).GetDaemonSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DaemonSet/GetDaemonSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonSetServer).GetDaemonSet(ctx, req.(*DaemonSetService))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonSet_PatchDaemonSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonSetService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonSetServer).PatchDaemonSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DaemonSet/PatchDaemonSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonSetServer).PatchDaemonSet(ctx, req.(*DaemonSetService))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonSet_PutDaemonSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonSetService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonSetServer).PutDaemonSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DaemonSet/PutDaemonSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonSetServer).PutDaemonSet(ctx, req.(*DaemonSetService))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaemonSet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DaemonSet",
	HandlerType: (*DaemonSetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDaemonSet",
			Handler:    _DaemonSet_CreateDaemonSet_Handler,
		},
		{
			MethodName: "DeleteDaemonSet",
			Handler:    _DaemonSet_DeleteDaemonSet_Handler,
		},
		{
			MethodName: "GetDaemonSet",
			Handler:    _DaemonSet_GetDaemonSet_Handler,
		},
		{
			MethodName: "PatchDaemonSet",
			Handler:    _DaemonSet_PatchDaemonSet_Handler,
		},
		{
			MethodName: "PutDaemonSet",
			Handler:    _DaemonSet_PutDaemonSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daemonset.proto",
}
