// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hpa.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HPA struct {
	ProjectId             string      `protobuf:"bytes,1,opt,name=ProjectId,proto3" json:"ProjectId,omitempty"`
	ServiceId             string      `protobuf:"bytes,2,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	Name                  string      `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ServiceType           string      `protobuf:"bytes,4,opt,name=ServiceType,proto3" json:"ServiceType,omitempty"`
	Token                 string      `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Status                string      `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	ServiceSubType        string      `protobuf:"bytes,7,opt,name=ServiceSubType,proto3" json:"ServiceSubType,omitempty"`
	ServiceDependencyInfo []string    `protobuf:"bytes,8,rep,name=ServiceDependencyInfo,proto3" json:"ServiceDependencyInfo,omitempty"`
	Namespace             string      `protobuf:"bytes,9,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	ServiceAttributes     *HpaSvcAttr `protobuf:"bytes,10,opt,name=ServiceAttributes,proto3" json:"ServiceAttributes,omitempty"`
	CompanyId             string      `protobuf:"bytes,11,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}    `json:"-"`
	XXX_unrecognized      []byte      `json:"-"`
	XXX_sizecache         int32       `json:"-"`
}

func (m *HPA) Reset()         { *m = HPA{} }
func (m *HPA) String() string { return proto.CompactTextString(m) }
func (*HPA) ProtoMessage()    {}
func (*HPA) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb39c4c53a32fc9, []int{0}
}

func (m *HPA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HPA.Unmarshal(m, b)
}
func (m *HPA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HPA.Marshal(b, m, deterministic)
}
func (m *HPA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HPA.Merge(m, src)
}
func (m *HPA) XXX_Size() int {
	return xxx_messageInfo_HPA.Size(m)
}
func (m *HPA) XXX_DiscardUnknown() {
	xxx_messageInfo_HPA.DiscardUnknown(m)
}

var xxx_messageInfo_HPA proto.InternalMessageInfo

func (m *HPA) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *HPA) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *HPA) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HPA) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *HPA) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *HPA) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HPA) GetServiceSubType() string {
	if m != nil {
		return m.ServiceSubType
	}
	return ""
}

func (m *HPA) GetServiceDependencyInfo() []string {
	if m != nil {
		return m.ServiceDependencyInfo
	}
	return nil
}

func (m *HPA) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *HPA) GetServiceAttributes() *HpaSvcAttr {
	if m != nil {
		return m.ServiceAttributes
	}
	return nil
}

func (m *HPA) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

type HpaSvcAttr struct {
	MinReplicas          int64               `protobuf:"varint,1,opt,name=MinReplicas,proto3" json:"MinReplicas,omitempty"`
	MaxReplicas          int64               `protobuf:"varint,2,opt,name=MaxReplicas,proto3" json:"MaxReplicas,omitempty"`
	CrossObjectVersion   *CrossObjectVersion `protobuf:"bytes,3,opt,name=CrossObjectVersion,proto3" json:"CrossObjectVersion,omitempty"`
	MetricValues         []*MetricValue      `protobuf:"bytes,4,rep,name=MetricValues,proto3" json:"MetricValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HpaSvcAttr) Reset()         { *m = HpaSvcAttr{} }
func (m *HpaSvcAttr) String() string { return proto.CompactTextString(m) }
func (*HpaSvcAttr) ProtoMessage()    {}
func (*HpaSvcAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb39c4c53a32fc9, []int{1}
}

func (m *HpaSvcAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HpaSvcAttr.Unmarshal(m, b)
}
func (m *HpaSvcAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HpaSvcAttr.Marshal(b, m, deterministic)
}
func (m *HpaSvcAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HpaSvcAttr.Merge(m, src)
}
func (m *HpaSvcAttr) XXX_Size() int {
	return xxx_messageInfo_HpaSvcAttr.Size(m)
}
func (m *HpaSvcAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_HpaSvcAttr.DiscardUnknown(m)
}

var xxx_messageInfo_HpaSvcAttr proto.InternalMessageInfo

func (m *HpaSvcAttr) GetMinReplicas() int64 {
	if m != nil {
		return m.MinReplicas
	}
	return 0
}

func (m *HpaSvcAttr) GetMaxReplicas() int64 {
	if m != nil {
		return m.MaxReplicas
	}
	return 0
}

func (m *HpaSvcAttr) GetCrossObjectVersion() *CrossObjectVersion {
	if m != nil {
		return m.CrossObjectVersion
	}
	return nil
}

func (m *HpaSvcAttr) GetMetricValues() []*MetricValue {
	if m != nil {
		return m.MetricValues
	}
	return nil
}

type CrossObjectVersion struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrossObjectVersion) Reset()         { *m = CrossObjectVersion{} }
func (m *CrossObjectVersion) String() string { return proto.CompactTextString(m) }
func (*CrossObjectVersion) ProtoMessage()    {}
func (*CrossObjectVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb39c4c53a32fc9, []int{2}
}

func (m *CrossObjectVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossObjectVersion.Unmarshal(m, b)
}
func (m *CrossObjectVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossObjectVersion.Marshal(b, m, deterministic)
}
func (m *CrossObjectVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossObjectVersion.Merge(m, src)
}
func (m *CrossObjectVersion) XXX_Size() int {
	return xxx_messageInfo_CrossObjectVersion.Size(m)
}
func (m *CrossObjectVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossObjectVersion.DiscardUnknown(m)
}

var xxx_messageInfo_CrossObjectVersion proto.InternalMessageInfo

func (m *CrossObjectVersion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CrossObjectVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CrossObjectVersion) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type MetricValue struct {
	TargetValueKind      string   `protobuf:"bytes,1,opt,name=TargetValueKind,proto3" json:"TargetValueKind,omitempty"`
	TargetValue          string   `protobuf:"bytes,2,opt,name=TargetValue,proto3" json:"TargetValue,omitempty"`
	TargetValueUnit      string   `protobuf:"bytes,3,opt,name=TargetValueUnit,proto3" json:"TargetValueUnit,omitempty"`
	ResourceKind         string   `protobuf:"bytes,4,opt,name=ResourceKind,proto3" json:"ResourceKind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricValue) Reset()         { *m = MetricValue{} }
func (m *MetricValue) String() string { return proto.CompactTextString(m) }
func (*MetricValue) ProtoMessage()    {}
func (*MetricValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb39c4c53a32fc9, []int{3}
}

func (m *MetricValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricValue.Unmarshal(m, b)
}
func (m *MetricValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricValue.Marshal(b, m, deterministic)
}
func (m *MetricValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricValue.Merge(m, src)
}
func (m *MetricValue) XXX_Size() int {
	return xxx_messageInfo_MetricValue.Size(m)
}
func (m *MetricValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricValue.DiscardUnknown(m)
}

var xxx_messageInfo_MetricValue proto.InternalMessageInfo

func (m *MetricValue) GetTargetValueKind() string {
	if m != nil {
		return m.TargetValueKind
	}
	return ""
}

func (m *MetricValue) GetTargetValue() string {
	if m != nil {
		return m.TargetValue
	}
	return ""
}

func (m *MetricValue) GetTargetValueUnit() string {
	if m != nil {
		return m.TargetValueUnit
	}
	return ""
}

func (m *MetricValue) GetResourceKind() string {
	if m != nil {
		return m.ResourceKind
	}
	return ""
}

func init() {
	proto.RegisterType((*HPA)(nil), "proto.HPA")
	proto.RegisterType((*HpaSvcAttr)(nil), "proto.HpaSvcAttr")
	proto.RegisterType((*CrossObjectVersion)(nil), "proto.CrossObjectVersion")
	proto.RegisterType((*MetricValue)(nil), "proto.MetricValue")
}

func init() { proto.RegisterFile("hpa.proto", fileDescriptor_deb39c4c53a32fc9) }

var fileDescriptor_deb39c4c53a32fc9 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x26, 0x4b, 0x3f, 0x96, 0x37, 0x13, 0x68, 0x16, 0x9b, 0xcc, 0x04, 0x52, 0x95, 0x03, 0xda,
	0xa9, 0x82, 0x82, 0xb8, 0xa2, 0x6a, 0x93, 0x58, 0x85, 0x06, 0x51, 0x3a, 0x7a, 0x45, 0xae, 0xfb,
	0xc2, 0x02, 0x9d, 0x1d, 0xd9, 0xce, 0x44, 0x8f, 0xfc, 0x1a, 0x7e, 0x10, 0xbf, 0x07, 0x89, 0xc4,
	0x76, 0xdb, 0xac, 0xeb, 0x61, 0x3d, 0x25, 0x7e, 0x9e, 0xc7, 0xef, 0xe7, 0x63, 0x88, 0xae, 0x0b,
	0xd6, 0x2f, 0x94, 0x34, 0x92, 0xb4, 0xed, 0xe7, 0xe4, 0x48, 0xa3, 0xba, 0xcd, 0x39, 0x2a, 0xd4,
	0x85, 0x14, 0x1a, 0x1d, 0x9b, 0xfc, 0x0e, 0x21, 0xbc, 0x48, 0x87, 0xe4, 0x39, 0x44, 0xa9, 0x92,
	0x3f, 0x90, 0x9b, 0xd1, 0x8c, 0x06, 0xbd, 0xe0, 0x34, 0xca, 0xd6, 0x40, 0xcd, 0x8e, 0xdd, 0xf5,
	0x8a, 0xdd, 0x73, 0xec, 0x0a, 0x20, 0x04, 0x5a, 0x9f, 0xd8, 0x0d, 0xd2, 0xd0, 0x12, 0xf6, 0x9f,
	0xf4, 0x20, 0xf6, 0x82, 0xab, 0x45, 0x81, 0xb4, 0x65, 0xa9, 0x26, 0x44, 0x9e, 0x42, 0xdb, 0xc8,
	0x9f, 0x28, 0x68, 0xdb, 0x72, 0xee, 0x40, 0x8e, 0xa1, 0x33, 0x36, 0xcc, 0x94, 0x9a, 0x76, 0x2c,
	0xec, 0x4f, 0xe4, 0x25, 0x3c, 0xf6, 0x97, 0xc7, 0xe5, 0xd4, 0x86, 0xec, 0x5a, 0x7e, 0x03, 0x25,
	0x6f, 0xe1, 0xc8, 0x23, 0xe7, 0x58, 0xa0, 0x98, 0xa1, 0xe0, 0x8b, 0x91, 0xf8, 0x26, 0xe9, 0x7e,
	0x2f, 0xac, 0xe4, 0xdb, 0xc9, 0xba, 0xbf, 0xba, 0x6a, 0x5d, 0x30, 0x8e, 0x34, 0x72, 0xfd, 0xad,
	0x00, 0xf2, 0x1e, 0x0e, 0xfd, 0xb5, 0xa1, 0x31, 0x2a, 0x9f, 0x96, 0x06, 0x35, 0x85, 0x4a, 0x15,
	0x0f, 0x0e, 0xdd, 0x18, 0xfb, 0x17, 0x05, 0x1b, 0xdf, 0xf2, 0x9a, 0xce, 0xee, 0x6b, 0xc9, 0x0b,
	0x00, 0x2e, 0x6f, 0x0a, 0x26, 0x16, 0x5f, 0xf3, 0x19, 0x8d, 0x5d, 0x7c, 0x8f, 0x8c, 0x66, 0xc9,
	0xdf, 0x00, 0x60, 0x1d, 0xa0, 0x1e, 0xdd, 0x65, 0x2e, 0x32, 0x2c, 0xe6, 0x39, 0x67, 0xda, 0x2e,
	0x23, 0xcc, 0x9a, 0x90, 0x55, 0xb0, 0x5f, 0x2b, 0xc5, 0x9e, 0x57, 0xac, 0x21, 0x32, 0x02, 0x72,
	0xa6, 0xa4, 0xd6, 0x9f, 0xa7, 0xf5, 0x06, 0x27, 0xa8, 0x74, 0x2e, 0x85, 0x5d, 0x50, 0x3c, 0x78,
	0xe6, 0x6b, 0xbe, 0x2f, 0xc8, 0xb6, 0x5c, 0x22, 0xef, 0xe0, 0xe0, 0x12, 0xab, 0x56, 0xf8, 0x84,
	0xcd, 0xcb, 0xaa, 0xf1, 0x56, 0x35, 0xc8, 0x78, 0x40, 0x7c, 0x90, 0x06, 0x95, 0xdd, 0xd1, 0x25,
	0x93, 0x6d, 0x25, 0xac, 0xbc, 0x12, 0x34, 0xbc, 0x42, 0xa1, 0xbb, 0xac, 0xd0, 0x79, 0xab, 0xdb,
	0x50, 0xdb, 0x5d, 0x7b, 0x67, 0xd5, 0xff, 0xc9, 0x9f, 0xa0, 0xea, 0x7e, 0x9d, 0x88, 0x9c, 0xc2,
	0x93, 0x2b, 0xa6, 0xbe, 0xa3, 0xb1, 0xc7, 0x8f, 0xb9, 0x58, 0xfa, 0x77, 0x13, 0xae, 0xc7, 0xd6,
	0x80, 0x7c, 0xae, 0x26, 0xb4, 0x11, 0xeb, 0x8b, 0xc8, 0x8d, 0x4f, 0xbd, 0x09, 0x93, 0x04, 0x0e,
	0x32, 0xd4, 0xb2, 0x54, 0xdc, 0xa5, 0x74, 0x06, 0xbf, 0x83, 0x0d, 0xfe, 0x05, 0x10, 0x56, 0xef,
	0x90, 0xbc, 0x86, 0xe8, 0x4c, 0x21, 0x33, 0x58, 0x3f, 0x34, 0x58, 0x3a, 0x26, 0x1d, 0x9e, 0x1c,
	0xfb, 0x7f, 0xef, 0x98, 0xcc, 0x3f, 0xcd, 0xe4, 0x11, 0xe9, 0x43, 0xe7, 0x03, 0x9a, 0x87, 0xeb,
	0xab, 0x14, 0xe7, 0x38, 0xc7, 0x5d, 0x52, 0xbc, 0x82, 0xfd, 0x94, 0x19, 0x7e, 0xbd, 0x53, 0x51,
	0x69, 0xf9, 0xf0, 0xa2, 0xa6, 0x1d, 0x4b, 0xbc, 0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xdd,
	0x4d, 0x6d, 0x8d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HpaClient is the client API for Hpa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HpaClient interface {
	CreateHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error)
	GetHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error)
	DeleteHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error)
	PatchHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error)
	PutHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type hpaClient struct {
	cc *grpc.ClientConn
}

func NewHpaClient(cc *grpc.ClientConn) HpaClient {
	return &hpaClient{cc}
}

func (c *hpaClient) CreateHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.hpa/CreateHPA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hpaClient) GetHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.hpa/GetHPA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hpaClient) DeleteHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.hpa/DeleteHPA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hpaClient) PatchHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.hpa/PatchHPA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hpaClient) PutHPA(ctx context.Context, in *HPA, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.hpa/PutHPA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HpaServer is the server API for Hpa service.
type HpaServer interface {
	CreateHPA(context.Context, *HPA) (*ServiceResponse, error)
	GetHPA(context.Context, *HPA) (*ServiceResponse, error)
	DeleteHPA(context.Context, *HPA) (*ServiceResponse, error)
	PatchHPA(context.Context, *HPA) (*ServiceResponse, error)
	PutHPA(context.Context, *HPA) (*ServiceResponse, error)
}

// UnimplementedHpaServer can be embedded to have forward compatible implementations.
type UnimplementedHpaServer struct {
}

func (*UnimplementedHpaServer) CreateHPA(ctx context.Context, req *HPA) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHPA not implemented")
}
func (*UnimplementedHpaServer) GetHPA(ctx context.Context, req *HPA) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHPA not implemented")
}
func (*UnimplementedHpaServer) DeleteHPA(ctx context.Context, req *HPA) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHPA not implemented")
}
func (*UnimplementedHpaServer) PatchHPA(ctx context.Context, req *HPA) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchHPA not implemented")
}
func (*UnimplementedHpaServer) PutHPA(ctx context.Context, req *HPA) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutHPA not implemented")
}

func RegisterHpaServer(s *grpc.Server, srv HpaServer) {
	s.RegisterService(&_Hpa_serviceDesc, srv)
}

func _Hpa_CreateHPA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HPA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HpaServer).CreateHPA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.hpa/CreateHPA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HpaServer).CreateHPA(ctx, req.(*HPA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hpa_GetHPA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HPA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HpaServer).GetHPA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.hpa/GetHPA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HpaServer).GetHPA(ctx, req.(*HPA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hpa_DeleteHPA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HPA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HpaServer).DeleteHPA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.hpa/DeleteHPA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HpaServer).DeleteHPA(ctx, req.(*HPA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hpa_PatchHPA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HPA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HpaServer).PatchHPA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.hpa/PatchHPA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HpaServer).PatchHPA(ctx, req.(*HPA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hpa_PutHPA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HPA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HpaServer).PutHPA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.hpa/PutHPA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HpaServer).PutHPA(ctx, req.(*HPA))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hpa_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.hpa",
	HandlerType: (*HpaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHPA",
			Handler:    _Hpa_CreateHPA_Handler,
		},
		{
			MethodName: "GetHPA",
			Handler:    _Hpa_GetHPA_Handler,
		},
		{
			MethodName: "DeleteHPA",
			Handler:    _Hpa_DeleteHPA_Handler,
		},
		{
			MethodName: "PatchHPA",
			Handler:    _Hpa_PatchHPA_Handler,
		},
		{
			MethodName: "PutHPA",
			Handler:    _Hpa_PutHPA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hpa.proto",
}
