// Code generated by protoc-gen-go. DO NOT EDIT.
// source: persistentvolume.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessMode int32

const (
	AccessMode_ReadWriteOnce AccessMode = 0
	AccessMode_ReadOnlyMany  AccessMode = 1
	AccessMode_ReadWriteMany AccessMode = 2
)

var AccessMode_name = map[int32]string{
	0: "ReadWriteOnce",
	1: "ReadOnlyMany",
	2: "ReadWriteMany",
}

var AccessMode_value = map[string]int32{
	"ReadWriteOnce": 0,
	"ReadOnlyMany":  1,
	"ReadWriteMany": 2,
}

func (x AccessMode) String() string {
	return proto.EnumName(AccessMode_name, int32(x))
}

func (AccessMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{0}
}

type PersistentVolumeMode int32

const (
	PersistentVolumeMode_Block      PersistentVolumeMode = 0
	PersistentVolumeMode_Filesystem PersistentVolumeMode = 1
)

var PersistentVolumeMode_name = map[int32]string{
	0: "Block",
	1: "Filesystem",
}

var PersistentVolumeMode_value = map[string]int32{
	"Block":      0,
	"Filesystem": 1,
}

func (x PersistentVolumeMode) String() string {
	return proto.EnumName(PersistentVolumeMode_name, int32(x))
}

func (PersistentVolumeMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{1}
}

type AzureDataDiskCachingMode int32

const (
	AzureDataDiskCachingMode_None      AzureDataDiskCachingMode = 0
	AzureDataDiskCachingMode_ReadOnly  AzureDataDiskCachingMode = 1
	AzureDataDiskCachingMode_ReadWrite AzureDataDiskCachingMode = 2
)

var AzureDataDiskCachingMode_name = map[int32]string{
	0: "None",
	1: "ReadOnly",
	2: "ReadWrite",
}

var AzureDataDiskCachingMode_value = map[string]int32{
	"None":      0,
	"ReadOnly":  1,
	"ReadWrite": 2,
}

func (x AzureDataDiskCachingMode) String() string {
	return proto.EnumName(AzureDataDiskCachingMode_name, int32(x))
}

func (AzureDataDiskCachingMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{2}
}

type AzureDataDiskKind int32

const (
	AzureDataDiskKind_Shared    AzureDataDiskKind = 0
	AzureDataDiskKind_Dedicated AzureDataDiskKind = 1
	AzureDataDiskKind_Managed   AzureDataDiskKind = 2
)

var AzureDataDiskKind_name = map[int32]string{
	0: "Shared",
	1: "Dedicated",
	2: "Managed",
}

var AzureDataDiskKind_value = map[string]int32{
	"Shared":    0,
	"Dedicated": 1,
	"Managed":   2,
}

func (x AzureDataDiskKind) String() string {
	return proto.EnumName(AzureDataDiskKind_name, int32(x))
}

func (AzureDataDiskKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{3}
}

type NodeSelectorOperator int32

const (
	NodeSelectorOperator_NodeSelectorOpIn            NodeSelectorOperator = 0
	NodeSelectorOperator_NodeSelectorOpNotIn         NodeSelectorOperator = 1
	NodeSelectorOperator_NodeSelectorOpExists        NodeSelectorOperator = 2
	NodeSelectorOperator_NodeSelectorOpDoesNotExists NodeSelectorOperator = 3
	NodeSelectorOperator_NodeSelectorOpGt            NodeSelectorOperator = 4
	NodeSelectorOperator_NodeSelectorOpLt            NodeSelectorOperator = 5
)

var NodeSelectorOperator_name = map[int32]string{
	0: "NodeSelectorOpIn",
	1: "NodeSelectorOpNotIn",
	2: "NodeSelectorOpExists",
	3: "NodeSelectorOpDoesNotExists",
	4: "NodeSelectorOpGt",
	5: "NodeSelectorOpLt",
}

var NodeSelectorOperator_value = map[string]int32{
	"NodeSelectorOpIn":            0,
	"NodeSelectorOpNotIn":         1,
	"NodeSelectorOpExists":        2,
	"NodeSelectorOpDoesNotExists": 3,
	"NodeSelectorOpGt":            4,
	"NodeSelectorOpLt":            5,
}

func (x NodeSelectorOperator) String() string {
	return proto.EnumName(NodeSelectorOperator_name, int32(x))
}

func (NodeSelectorOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{4}
}

type PersistentVolumeService struct {
	ProjectId            string                      `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId            string                      `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name                 string                      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version              string                      `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	ServiceType          string                      `protobuf:"bytes,5,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ServiceSubType       string                      `protobuf:"bytes,6,opt,name=service_sub_type,json=serviceSubType,proto3" json:"service_sub_type,omitempty"`
	Token                string                      `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	CompanyId            string                      `protobuf:"bytes,8,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ServiceAttributes    *PersistentVolumeAttributes `protobuf:"bytes,9,opt,name=service_attributes,json=serviceAttributes,proto3" json:"service_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PersistentVolumeService) Reset()         { *m = PersistentVolumeService{} }
func (m *PersistentVolumeService) String() string { return proto.CompactTextString(m) }
func (*PersistentVolumeService) ProtoMessage()    {}
func (*PersistentVolumeService) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{0}
}

func (m *PersistentVolumeService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistentVolumeService.Unmarshal(m, b)
}
func (m *PersistentVolumeService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistentVolumeService.Marshal(b, m, deterministic)
}
func (m *PersistentVolumeService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistentVolumeService.Merge(m, src)
}
func (m *PersistentVolumeService) XXX_Size() int {
	return xxx_messageInfo_PersistentVolumeService.Size(m)
}
func (m *PersistentVolumeService) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistentVolumeService.DiscardUnknown(m)
}

var xxx_messageInfo_PersistentVolumeService proto.InternalMessageInfo

func (m *PersistentVolumeService) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *PersistentVolumeService) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *PersistentVolumeService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersistentVolumeService) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PersistentVolumeService) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *PersistentVolumeService) GetServiceSubType() string {
	if m != nil {
		return m.ServiceSubType
	}
	return ""
}

func (m *PersistentVolumeService) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PersistentVolumeService) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *PersistentVolumeService) GetServiceAttributes() *PersistentVolumeAttributes {
	if m != nil {
		return m.ServiceAttributes
	}
	return nil
}

type PersistentVolumeAttributes struct {
	Labels                 map[string]string       `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ReclaimPolicy          ReclaimPolicy           `protobuf:"varint,2,opt,name=reclaimPolicy,proto3,enum=proto.ReclaimPolicy" json:"reclaimPolicy,omitempty"`
	AccessMode             []AccessMode            `protobuf:"varint,3,rep,packed,name=accessMode,proto3,enum=proto.AccessMode" json:"accessMode,omitempty"`
	Capcity                string                  `protobuf:"bytes,4,opt,name=capcity,proto3" json:"capcity,omitempty"`
	PersistentVolumeSource *PersistentVolumeSource `protobuf:"bytes,5,opt,name=persistentVolumeSource,proto3" json:"persistentVolumeSource,omitempty"`
	StorageClassName       string                  `protobuf:"bytes,6,opt,name=storageClassName,proto3" json:"storageClassName,omitempty"`
	MountOptions           []string                `protobuf:"bytes,7,rep,name=mountOptions,proto3" json:"mountOptions,omitempty"`
	VolumeMode             PersistentVolumeMode    `protobuf:"varint,8,opt,name=volumeMode,proto3,enum=proto.PersistentVolumeMode" json:"volumeMode,omitempty"`
	NodeAffinity           *VolumeNodeAffinity     `protobuf:"bytes,9,opt,name=nodeAffinity,proto3" json:"nodeAffinity,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *PersistentVolumeAttributes) Reset()         { *m = PersistentVolumeAttributes{} }
func (m *PersistentVolumeAttributes) String() string { return proto.CompactTextString(m) }
func (*PersistentVolumeAttributes) ProtoMessage()    {}
func (*PersistentVolumeAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{1}
}

func (m *PersistentVolumeAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistentVolumeAttributes.Unmarshal(m, b)
}
func (m *PersistentVolumeAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistentVolumeAttributes.Marshal(b, m, deterministic)
}
func (m *PersistentVolumeAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistentVolumeAttributes.Merge(m, src)
}
func (m *PersistentVolumeAttributes) XXX_Size() int {
	return xxx_messageInfo_PersistentVolumeAttributes.Size(m)
}
func (m *PersistentVolumeAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistentVolumeAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_PersistentVolumeAttributes proto.InternalMessageInfo

func (m *PersistentVolumeAttributes) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *PersistentVolumeAttributes) GetReclaimPolicy() ReclaimPolicy {
	if m != nil {
		return m.ReclaimPolicy
	}
	return ReclaimPolicy_Retain
}

func (m *PersistentVolumeAttributes) GetAccessMode() []AccessMode {
	if m != nil {
		return m.AccessMode
	}
	return nil
}

func (m *PersistentVolumeAttributes) GetCapcity() string {
	if m != nil {
		return m.Capcity
	}
	return ""
}

func (m *PersistentVolumeAttributes) GetPersistentVolumeSource() *PersistentVolumeSource {
	if m != nil {
		return m.PersistentVolumeSource
	}
	return nil
}

func (m *PersistentVolumeAttributes) GetStorageClassName() string {
	if m != nil {
		return m.StorageClassName
	}
	return ""
}

func (m *PersistentVolumeAttributes) GetMountOptions() []string {
	if m != nil {
		return m.MountOptions
	}
	return nil
}

func (m *PersistentVolumeAttributes) GetVolumeMode() PersistentVolumeMode {
	if m != nil {
		return m.VolumeMode
	}
	return PersistentVolumeMode_Block
}

func (m *PersistentVolumeAttributes) GetNodeAffinity() *VolumeNodeAffinity {
	if m != nil {
		return m.NodeAffinity
	}
	return nil
}

type PersistentVolumeSource struct {
	GcpPd                *GCPPD     `protobuf:"bytes,1,opt,name=gcpPd,proto3" json:"gcpPd,omitempty"`
	AwsEbs               *AWSEBS    `protobuf:"bytes,2,opt,name=awsEbs,proto3" json:"awsEbs,omitempty"`
	AzureDisk            *AzureDisk `protobuf:"bytes,3,opt,name=azureDisk,proto3" json:"azureDisk,omitempty"`
	AzureFile            *AzureFile `protobuf:"bytes,4,opt,name=azureFile,proto3" json:"azureFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PersistentVolumeSource) Reset()         { *m = PersistentVolumeSource{} }
func (m *PersistentVolumeSource) String() string { return proto.CompactTextString(m) }
func (*PersistentVolumeSource) ProtoMessage()    {}
func (*PersistentVolumeSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{2}
}

func (m *PersistentVolumeSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistentVolumeSource.Unmarshal(m, b)
}
func (m *PersistentVolumeSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistentVolumeSource.Marshal(b, m, deterministic)
}
func (m *PersistentVolumeSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistentVolumeSource.Merge(m, src)
}
func (m *PersistentVolumeSource) XXX_Size() int {
	return xxx_messageInfo_PersistentVolumeSource.Size(m)
}
func (m *PersistentVolumeSource) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistentVolumeSource.DiscardUnknown(m)
}

var xxx_messageInfo_PersistentVolumeSource proto.InternalMessageInfo

func (m *PersistentVolumeSource) GetGcpPd() *GCPPD {
	if m != nil {
		return m.GcpPd
	}
	return nil
}

func (m *PersistentVolumeSource) GetAwsEbs() *AWSEBS {
	if m != nil {
		return m.AwsEbs
	}
	return nil
}

func (m *PersistentVolumeSource) GetAzureDisk() *AzureDisk {
	if m != nil {
		return m.AzureDisk
	}
	return nil
}

func (m *PersistentVolumeSource) GetAzureFile() *AzureFile {
	if m != nil {
		return m.AzureFile
	}
	return nil
}

type GCPPD struct {
	PdName               string   `protobuf:"bytes,1,opt,name=pdName,proto3" json:"pdName,omitempty"`
	FileSystem           string   `protobuf:"bytes,2,opt,name=fileSystem,proto3" json:"fileSystem,omitempty"`
	Partation            int64    `protobuf:"varint,3,opt,name=partation,proto3" json:"partation,omitempty"`
	ReadOnly             bool     `protobuf:"varint,4,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCPPD) Reset()         { *m = GCPPD{} }
func (m *GCPPD) String() string { return proto.CompactTextString(m) }
func (*GCPPD) ProtoMessage()    {}
func (*GCPPD) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{3}
}

func (m *GCPPD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCPPD.Unmarshal(m, b)
}
func (m *GCPPD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCPPD.Marshal(b, m, deterministic)
}
func (m *GCPPD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCPPD.Merge(m, src)
}
func (m *GCPPD) XXX_Size() int {
	return xxx_messageInfo_GCPPD.Size(m)
}
func (m *GCPPD) XXX_DiscardUnknown() {
	xxx_messageInfo_GCPPD.DiscardUnknown(m)
}

var xxx_messageInfo_GCPPD proto.InternalMessageInfo

func (m *GCPPD) GetPdName() string {
	if m != nil {
		return m.PdName
	}
	return ""
}

func (m *GCPPD) GetFileSystem() string {
	if m != nil {
		return m.FileSystem
	}
	return ""
}

func (m *GCPPD) GetPartation() int64 {
	if m != nil {
		return m.Partation
	}
	return 0
}

func (m *GCPPD) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

type AWSEBS struct {
	VolumeId             string   `protobuf:"bytes,1,opt,name=volumeId,proto3" json:"volumeId,omitempty"`
	FileSystem           string   `protobuf:"bytes,2,opt,name=fileSystem,proto3" json:"fileSystem,omitempty"`
	Partation            int64    `protobuf:"varint,3,opt,name=partation,proto3" json:"partation,omitempty"`
	ReadOnly             bool     `protobuf:"varint,4,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSEBS) Reset()         { *m = AWSEBS{} }
func (m *AWSEBS) String() string { return proto.CompactTextString(m) }
func (*AWSEBS) ProtoMessage()    {}
func (*AWSEBS) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{4}
}

func (m *AWSEBS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSEBS.Unmarshal(m, b)
}
func (m *AWSEBS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSEBS.Marshal(b, m, deterministic)
}
func (m *AWSEBS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSEBS.Merge(m, src)
}
func (m *AWSEBS) XXX_Size() int {
	return xxx_messageInfo_AWSEBS.Size(m)
}
func (m *AWSEBS) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSEBS.DiscardUnknown(m)
}

var xxx_messageInfo_AWSEBS proto.InternalMessageInfo

func (m *AWSEBS) GetVolumeId() string {
	if m != nil {
		return m.VolumeId
	}
	return ""
}

func (m *AWSEBS) GetFileSystem() string {
	if m != nil {
		return m.FileSystem
	}
	return ""
}

func (m *AWSEBS) GetPartation() int64 {
	if m != nil {
		return m.Partation
	}
	return 0
}

func (m *AWSEBS) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

type AzureDisk struct {
	CachingMode          AzureDataDiskCachingMode `protobuf:"varint,1,opt,name=cachingMode,proto3,enum=proto.AzureDataDiskCachingMode" json:"cachingMode,omitempty"`
	Kind                 AzureDataDiskKind        `protobuf:"varint,6,opt,name=kind,proto3,enum=proto.AzureDataDiskKind" json:"kind,omitempty"`
	FileSystem           string                   `protobuf:"bytes,2,opt,name=fileSystem,proto3" json:"fileSystem,omitempty"`
	DiskName             string                   `protobuf:"bytes,3,opt,name=diskName,proto3" json:"diskName,omitempty"`
	ReadOnly             bool                     `protobuf:"varint,4,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	DiskURI              string                   `protobuf:"bytes,5,opt,name=diskURI,proto3" json:"diskURI,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AzureDisk) Reset()         { *m = AzureDisk{} }
func (m *AzureDisk) String() string { return proto.CompactTextString(m) }
func (*AzureDisk) ProtoMessage()    {}
func (*AzureDisk) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{5}
}

func (m *AzureDisk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AzureDisk.Unmarshal(m, b)
}
func (m *AzureDisk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AzureDisk.Marshal(b, m, deterministic)
}
func (m *AzureDisk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AzureDisk.Merge(m, src)
}
func (m *AzureDisk) XXX_Size() int {
	return xxx_messageInfo_AzureDisk.Size(m)
}
func (m *AzureDisk) XXX_DiscardUnknown() {
	xxx_messageInfo_AzureDisk.DiscardUnknown(m)
}

var xxx_messageInfo_AzureDisk proto.InternalMessageInfo

func (m *AzureDisk) GetCachingMode() AzureDataDiskCachingMode {
	if m != nil {
		return m.CachingMode
	}
	return AzureDataDiskCachingMode_None
}

func (m *AzureDisk) GetKind() AzureDataDiskKind {
	if m != nil {
		return m.Kind
	}
	return AzureDataDiskKind_Shared
}

func (m *AzureDisk) GetFileSystem() string {
	if m != nil {
		return m.FileSystem
	}
	return ""
}

func (m *AzureDisk) GetDiskName() string {
	if m != nil {
		return m.DiskName
	}
	return ""
}

func (m *AzureDisk) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *AzureDisk) GetDiskURI() string {
	if m != nil {
		return m.DiskURI
	}
	return ""
}

type AzureFile struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	ShareName            string   `protobuf:"bytes,2,opt,name=shareName,proto3" json:"shareName,omitempty"`
	ReadOnly             bool     `protobuf:"varint,3,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	SecretNamespace      string   `protobuf:"bytes,4,opt,name=secretNamespace,proto3" json:"secretNamespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AzureFile) Reset()         { *m = AzureFile{} }
func (m *AzureFile) String() string { return proto.CompactTextString(m) }
func (*AzureFile) ProtoMessage()    {}
func (*AzureFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{6}
}

func (m *AzureFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AzureFile.Unmarshal(m, b)
}
func (m *AzureFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AzureFile.Marshal(b, m, deterministic)
}
func (m *AzureFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AzureFile.Merge(m, src)
}
func (m *AzureFile) XXX_Size() int {
	return xxx_messageInfo_AzureFile.Size(m)
}
func (m *AzureFile) XXX_DiscardUnknown() {
	xxx_messageInfo_AzureFile.DiscardUnknown(m)
}

var xxx_messageInfo_AzureFile proto.InternalMessageInfo

func (m *AzureFile) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *AzureFile) GetShareName() string {
	if m != nil {
		return m.ShareName
	}
	return ""
}

func (m *AzureFile) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *AzureFile) GetSecretNamespace() string {
	if m != nil {
		return m.SecretNamespace
	}
	return ""
}

type VolumeNodeAffinity struct {
	Required             *NodeSelector `protobuf:"bytes,1,opt,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VolumeNodeAffinity) Reset()         { *m = VolumeNodeAffinity{} }
func (m *VolumeNodeAffinity) String() string { return proto.CompactTextString(m) }
func (*VolumeNodeAffinity) ProtoMessage()    {}
func (*VolumeNodeAffinity) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{7}
}

func (m *VolumeNodeAffinity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeNodeAffinity.Unmarshal(m, b)
}
func (m *VolumeNodeAffinity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeNodeAffinity.Marshal(b, m, deterministic)
}
func (m *VolumeNodeAffinity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeNodeAffinity.Merge(m, src)
}
func (m *VolumeNodeAffinity) XXX_Size() int {
	return xxx_messageInfo_VolumeNodeAffinity.Size(m)
}
func (m *VolumeNodeAffinity) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeNodeAffinity.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeNodeAffinity proto.InternalMessageInfo

func (m *VolumeNodeAffinity) GetRequired() *NodeSelector {
	if m != nil {
		return m.Required
	}
	return nil
}

type NodeSelector struct {
	NodeSelectorTerms    []*NodeSelectorTerm `protobuf:"bytes,1,rep,name=nodeSelectorTerms,proto3" json:"nodeSelectorTerms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NodeSelector) Reset()         { *m = NodeSelector{} }
func (m *NodeSelector) String() string { return proto.CompactTextString(m) }
func (*NodeSelector) ProtoMessage()    {}
func (*NodeSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{8}
}

func (m *NodeSelector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSelector.Unmarshal(m, b)
}
func (m *NodeSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSelector.Marshal(b, m, deterministic)
}
func (m *NodeSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSelector.Merge(m, src)
}
func (m *NodeSelector) XXX_Size() int {
	return xxx_messageInfo_NodeSelector.Size(m)
}
func (m *NodeSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSelector.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSelector proto.InternalMessageInfo

func (m *NodeSelector) GetNodeSelectorTerms() []*NodeSelectorTerm {
	if m != nil {
		return m.NodeSelectorTerms
	}
	return nil
}

type NodeSelectorTerm struct {
	MatchExpressions     []*NodeSelectorRequirement `protobuf:"bytes,1,rep,name=matchExpressions,proto3" json:"matchExpressions,omitempty"`
	MatchFields          []*NodeSelectorRequirement `protobuf:"bytes,2,rep,name=matchFields,proto3" json:"matchFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NodeSelectorTerm) Reset()         { *m = NodeSelectorTerm{} }
func (m *NodeSelectorTerm) String() string { return proto.CompactTextString(m) }
func (*NodeSelectorTerm) ProtoMessage()    {}
func (*NodeSelectorTerm) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{9}
}

func (m *NodeSelectorTerm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSelectorTerm.Unmarshal(m, b)
}
func (m *NodeSelectorTerm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSelectorTerm.Marshal(b, m, deterministic)
}
func (m *NodeSelectorTerm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSelectorTerm.Merge(m, src)
}
func (m *NodeSelectorTerm) XXX_Size() int {
	return xxx_messageInfo_NodeSelectorTerm.Size(m)
}
func (m *NodeSelectorTerm) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSelectorTerm.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSelectorTerm proto.InternalMessageInfo

func (m *NodeSelectorTerm) GetMatchExpressions() []*NodeSelectorRequirement {
	if m != nil {
		return m.MatchExpressions
	}
	return nil
}

func (m *NodeSelectorTerm) GetMatchFields() []*NodeSelectorRequirement {
	if m != nil {
		return m.MatchFields
	}
	return nil
}

type NodeSelectorRequirement struct {
	Key                  string               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Operator             NodeSelectorOperator `protobuf:"varint,2,opt,name=operator,proto3,enum=proto.NodeSelectorOperator" json:"operator,omitempty"`
	Values               []string             `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NodeSelectorRequirement) Reset()         { *m = NodeSelectorRequirement{} }
func (m *NodeSelectorRequirement) String() string { return proto.CompactTextString(m) }
func (*NodeSelectorRequirement) ProtoMessage()    {}
func (*NodeSelectorRequirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_724324990baa6ac6, []int{10}
}

func (m *NodeSelectorRequirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSelectorRequirement.Unmarshal(m, b)
}
func (m *NodeSelectorRequirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSelectorRequirement.Marshal(b, m, deterministic)
}
func (m *NodeSelectorRequirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSelectorRequirement.Merge(m, src)
}
func (m *NodeSelectorRequirement) XXX_Size() int {
	return xxx_messageInfo_NodeSelectorRequirement.Size(m)
}
func (m *NodeSelectorRequirement) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSelectorRequirement.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSelectorRequirement proto.InternalMessageInfo

func (m *NodeSelectorRequirement) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NodeSelectorRequirement) GetOperator() NodeSelectorOperator {
	if m != nil {
		return m.Operator
	}
	return NodeSelectorOperator_NodeSelectorOpIn
}

func (m *NodeSelectorRequirement) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.AccessMode", AccessMode_name, AccessMode_value)
	proto.RegisterEnum("proto.PersistentVolumeMode", PersistentVolumeMode_name, PersistentVolumeMode_value)
	proto.RegisterEnum("proto.AzureDataDiskCachingMode", AzureDataDiskCachingMode_name, AzureDataDiskCachingMode_value)
	proto.RegisterEnum("proto.AzureDataDiskKind", AzureDataDiskKind_name, AzureDataDiskKind_value)
	proto.RegisterEnum("proto.NodeSelectorOperator", NodeSelectorOperator_name, NodeSelectorOperator_value)
	proto.RegisterType((*PersistentVolumeService)(nil), "proto.PersistentVolumeService")
	proto.RegisterType((*PersistentVolumeAttributes)(nil), "proto.PersistentVolumeAttributes")
	proto.RegisterMapType((map[string]string)(nil), "proto.PersistentVolumeAttributes.LabelsEntry")
	proto.RegisterType((*PersistentVolumeSource)(nil), "proto.PersistentVolumeSource")
	proto.RegisterType((*GCPPD)(nil), "proto.GCPPD")
	proto.RegisterType((*AWSEBS)(nil), "proto.AWSEBS")
	proto.RegisterType((*AzureDisk)(nil), "proto.AzureDisk")
	proto.RegisterType((*AzureFile)(nil), "proto.AzureFile")
	proto.RegisterType((*VolumeNodeAffinity)(nil), "proto.VolumeNodeAffinity")
	proto.RegisterType((*NodeSelector)(nil), "proto.NodeSelector")
	proto.RegisterType((*NodeSelectorTerm)(nil), "proto.NodeSelectorTerm")
	proto.RegisterType((*NodeSelectorRequirement)(nil), "proto.NodeSelectorRequirement")
}

func init() { proto.RegisterFile("persistentvolume.proto", fileDescriptor_724324990baa6ac6) }

var fileDescriptor_724324990baa6ac6 = []byte{
	// 1172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0xf3, 0xd7, 0xe4, 0x24, 0x2d, 0xee, 0xb4, 0xa4, 0x26, 0x65, 0xbb, 0x5d, 0x4b, 0x48,
	0x51, 0x04, 0x45, 0x1b, 0x2e, 0x80, 0x5d, 0x21, 0xd1, 0x6d, 0xb2, 0x55, 0x60, 0x9b, 0x84, 0xc9,
	0x96, 0xbd, 0x44, 0x13, 0x7b, 0xda, 0x9a, 0x38, 0xb6, 0xf1, 0x4c, 0xca, 0x06, 0x21, 0x5e, 0x81,
	0x57, 0xe0, 0x01, 0x90, 0x78, 0x08, 0xee, 0x78, 0x03, 0x5e, 0x82, 0x67, 0x40, 0xf3, 0xe3, 0xc4,
	0xf9, 0x63, 0xb9, 0xe8, 0x5e, 0xb5, 0xe7, 0x3b, 0xdf, 0x39, 0x73, 0xfe, 0x1d, 0xa8, 0x46, 0x34,
	0x66, 0x1e, 0xe3, 0x34, 0xe0, 0x77, 0xa1, 0x3f, 0x19, 0xd3, 0xd3, 0x28, 0x0e, 0x79, 0x88, 0xf2,
	0xf2, 0x4f, 0x0d, 0x31, 0x1e, 0xc6, 0xe4, 0x86, 0x3a, 0x3e, 0x61, 0x4c, 0xa9, 0x6a, 0x3b, 0x8c,
	0xc6, 0x77, 0x9e, 0xa3, 0x99, 0xf6, 0xdf, 0x19, 0x38, 0xec, 0xcf, 0x9c, 0x7c, 0x2b, 0x9d, 0x0c,
	0x14, 0x03, 0x3d, 0x00, 0x88, 0xe2, 0xf0, 0x7b, 0xea, 0xf0, 0xef, 0x3c, 0xd7, 0x32, 0x4e, 0x8c,
	0x7a, 0x09, 0x97, 0x34, 0xd2, 0x71, 0x85, 0x5a, 0xfb, 0x12, 0xea, 0x8c, 0x52, 0x6b, 0xa4, 0xe3,
	0x22, 0x04, 0xb9, 0x80, 0x8c, 0xa9, 0x95, 0x95, 0x0a, 0xf9, 0x3f, 0xb2, 0x60, 0xfb, 0x4e, 0x3c,
	0x16, 0x06, 0x56, 0x4e, 0xc2, 0x89, 0x88, 0x1e, 0x41, 0x25, 0x71, 0xc6, 0xa7, 0x11, 0xb5, 0xf2,
	0x52, 0x5d, 0xd6, 0xd8, 0xcb, 0x69, 0x44, 0x51, 0x1d, 0xcc, 0x84, 0xc2, 0x26, 0x43, 0x45, 0x2b,
	0x48, 0xda, 0xae, 0xc6, 0x07, 0x93, 0xa1, 0x64, 0x1e, 0x40, 0x9e, 0x87, 0x23, 0x1a, 0x58, 0xdb,
	0x52, 0xad, 0x04, 0x11, 0xaf, 0x13, 0x8e, 0x23, 0x12, 0x4c, 0x45, 0xbc, 0x45, 0x15, 0xaf, 0x46,
	0x3a, 0x2e, 0xea, 0x03, 0x4a, 0xdc, 0x13, 0xce, 0x63, 0x6f, 0x38, 0xe1, 0x94, 0x59, 0xa5, 0x13,
	0xa3, 0x5e, 0x6e, 0x3e, 0x52, 0xd5, 0x3a, 0x5d, 0xae, 0xd4, 0xd9, 0x8c, 0x88, 0xf7, 0xb4, 0xf1,
	0x1c, 0xb2, 0xff, 0xca, 0x41, 0x6d, 0xb3, 0x05, 0x6a, 0x43, 0xc1, 0x27, 0x43, 0xea, 0x33, 0xcb,
	0x38, 0xc9, 0xd6, 0xcb, 0xcd, 0x8f, 0xde, 0xf8, 0xc8, 0xe9, 0x0b, 0xc9, 0x6f, 0x07, 0x3c, 0x9e,
	0x62, 0x6d, 0x8c, 0x9e, 0xc0, 0x4e, 0x2c, 0x3a, 0xec, 0x8d, 0xfb, 0xa1, 0xef, 0x39, 0x53, 0xd9,
	0x89, 0xdd, 0xe6, 0x81, 0xf6, 0x86, 0xd3, 0x3a, 0xbc, 0x48, 0x45, 0x8f, 0x01, 0x88, 0xe3, 0x50,
	0xc6, 0x2e, 0x43, 0x57, 0x74, 0x2a, 0x5b, 0xdf, 0x6d, 0xee, 0x69, 0xc3, 0xb3, 0x99, 0x02, 0xa7,
	0x48, 0xa2, 0x85, 0x0e, 0x89, 0x1c, 0x8f, 0x4f, 0x93, 0x16, 0x6a, 0x11, 0x5d, 0xa5, 0xc7, 0x51,
	0x4f, 0x52, 0x38, 0x89, 0x1d, 0xd5, 0xcc, 0x72, 0xf3, 0xc1, 0x86, 0xfc, 0x14, 0x09, 0x6f, 0x30,
	0x46, 0x0d, 0x30, 0xf5, 0x18, 0x9f, 0x8b, 0x31, 0xee, 0x8a, 0x99, 0x52, 0x6d, 0x5f, 0xc1, 0x91,
	0x0d, 0x95, 0x71, 0x38, 0x09, 0x78, 0x2f, 0xe2, 0x5e, 0x18, 0x30, 0x6b, 0xfb, 0x24, 0x5b, 0x2f,
	0xe1, 0x05, 0x0c, 0x3d, 0x05, 0x50, 0xbb, 0x22, 0x73, 0x2e, 0xca, 0x62, 0x1d, 0x6d, 0x08, 0x4d,
	0x65, 0x3f, 0xa7, 0xa3, 0x2f, 0xa0, 0x12, 0x84, 0x2e, 0x3d, 0xbb, 0xbe, 0xf6, 0x02, 0x51, 0x02,
	0x35, 0x1e, 0xef, 0x69, 0x73, 0x65, 0xd4, 0x4d, 0x11, 0xf0, 0x02, 0xbd, 0xf6, 0x39, 0x94, 0x53,
	0x2d, 0x44, 0x26, 0x64, 0x47, 0x74, 0xaa, 0x37, 0x4b, 0xfc, 0x2b, 0x26, 0xf7, 0x8e, 0xf8, 0x13,
	0xaa, 0xd7, 0x49, 0x09, 0x4f, 0x32, 0x9f, 0x19, 0xf6, 0x9f, 0x06, 0x54, 0xd7, 0x57, 0x0e, 0xd9,
	0x90, 0xbf, 0x71, 0xa2, 0xbe, 0x5a, 0xd1, 0x72, 0xb3, 0xa2, 0xa3, 0xb9, 0x38, 0xef, 0xf7, 0x5b,
	0x58, 0xa9, 0xd0, 0x07, 0x50, 0x20, 0x3f, 0xb2, 0xf6, 0x90, 0x49, 0xcf, 0xe5, 0xe6, 0x4e, 0xd2,
	0xe5, 0x57, 0x83, 0xf6, 0xb3, 0x01, 0xd6, 0x4a, 0x74, 0x0a, 0x25, 0xf2, 0xd3, 0x24, 0xa6, 0x2d,
	0x8f, 0x8d, 0xe4, 0xe6, 0x96, 0x9b, 0x66, 0xc2, 0x4c, 0x70, 0x3c, 0xa7, 0xcc, 0xf8, 0xcf, 0x3d,
	0x9f, 0xca, 0x79, 0x58, 0xe2, 0x0b, 0x1c, 0xcf, 0x29, 0xf6, 0x14, 0xf2, 0x32, 0x2c, 0x54, 0x85,
	0x42, 0xe4, 0xca, 0x5e, 0xaa, 0xec, 0xb5, 0x84, 0x8e, 0x01, 0xae, 0x3d, 0x9f, 0x0e, 0xa6, 0x8c,
	0xd3, 0xb1, 0xae, 0x42, 0x0a, 0x41, 0xef, 0x43, 0x29, 0x22, 0x31, 0x27, 0xa2, 0x97, 0x32, 0xc0,
	0x2c, 0x9e, 0x03, 0xa8, 0x06, 0xc5, 0x98, 0x12, 0xb7, 0x17, 0xf8, 0x6a, 0x3a, 0x8b, 0x78, 0x26,
	0xdb, 0xbf, 0x40, 0x41, 0x25, 0x2b, 0x58, 0xaa, 0xa5, 0x9d, 0xe4, 0xaa, 0xcd, 0xe4, 0xb7, 0xf8,
	0xfe, 0x3f, 0x06, 0x94, 0x66, 0x35, 0x44, 0x67, 0x50, 0x76, 0x88, 0x73, 0xeb, 0x05, 0x37, 0x72,
	0x0c, 0x0d, 0x39, 0x86, 0x0f, 0x17, 0x4a, 0x4d, 0x38, 0x11, 0xd4, 0xf3, 0x39, 0x0d, 0xa7, 0x6d,
	0xd0, 0x87, 0x90, 0x1b, 0x79, 0x81, 0x2b, 0x97, 0x61, 0xb7, 0x69, 0xad, 0xb3, 0xfd, 0xda, 0x0b,
	0x5c, 0x2c, 0x59, 0x6f, 0x4c, 0xac, 0x06, 0x45, 0xd7, 0x63, 0xa3, 0xee, 0xfc, 0x64, 0xcf, 0xe4,
	0xff, 0x4a, 0x4b, 0xdc, 0x03, 0xc1, 0xbb, 0xc2, 0x1d, 0x7d, 0xb3, 0x13, 0xd1, 0xfe, 0x35, 0x49,
	0x58, 0x74, 0x5e, 0xbc, 0xcf, 0xa8, 0x13, 0x53, 0x9e, 0x6a, 0x7a, 0x0a, 0x11, 0x85, 0x65, 0xb7,
	0x24, 0xa6, 0x52, 0x9d, 0x7c, 0x4c, 0x12, 0x60, 0x21, 0x82, 0xec, 0x52, 0x04, 0x75, 0x78, 0x67,
	0xee, 0x87, 0x45, 0xc4, 0xa1, 0xfa, 0x32, 0x2d, 0xc3, 0x76, 0x1b, 0xd0, 0xea, 0x8a, 0xa2, 0x8f,
	0x85, 0xef, 0x1f, 0x26, 0x5e, 0x4c, 0x93, 0x0d, 0xda, 0xd7, 0xb5, 0x14, 0xb4, 0x01, 0xf5, 0xa9,
	0xc3, 0xc3, 0x18, 0xcf, 0x48, 0xf6, 0x15, 0x54, 0xd2, 0x1a, 0xd4, 0x86, 0xbd, 0x20, 0x25, 0xbf,
	0xa4, 0xf1, 0x38, 0xb9, 0xe9, 0x87, 0x6b, 0x3c, 0x09, 0x3d, 0x5e, 0xb5, 0xb0, 0x7f, 0x33, 0xc0,
	0x5c, 0xe6, 0xa1, 0xaf, 0xc0, 0x1c, 0x13, 0xee, 0xdc, 0xb6, 0x5f, 0x47, 0x31, 0x65, 0x4c, 0x5e,
	0x35, 0xe5, 0xfa, 0x78, 0x5d, 0x90, 0x2a, 0xc4, 0x31, 0x0d, 0x38, 0x5e, 0xb1, 0x43, 0x5f, 0x42,
	0x59, 0x62, 0xcf, 0x3d, 0xea, 0xbb, 0xe2, 0x10, 0xfc, 0x1f, 0x37, 0x69, 0x13, 0xfb, 0x67, 0x38,
	0xdc, 0xc0, 0x5b, 0x73, 0xcb, 0x3e, 0x85, 0x62, 0x18, 0xd1, 0x98, 0xf0, 0x30, 0xd6, 0xdf, 0xa4,
	0xa3, 0x35, 0x6f, 0xf5, 0x34, 0x05, 0xcf, 0xc8, 0xe2, 0x36, 0xc8, 0xbb, 0xc7, 0xe4, 0x17, 0xa9,
	0x84, 0xb5, 0xd4, 0x68, 0x01, 0xcc, 0x3f, 0x4a, 0x68, 0x0f, 0x76, 0x30, 0x25, 0xee, 0xab, 0xd8,
	0xe3, 0xb4, 0x17, 0x38, 0xd4, 0xdc, 0x42, 0x26, 0x54, 0xb0, 0x9e, 0x8a, 0x4b, 0x12, 0x4c, 0x4d,
	0x63, 0x81, 0x24, 0xa1, 0x4c, 0xe3, 0x31, 0x1c, 0xac, 0x3b, 0xf3, 0xa8, 0x04, 0xf9, 0x67, 0x7e,
	0xe8, 0x8c, 0xcc, 0x2d, 0xb4, 0x0b, 0x20, 0x66, 0x96, 0xc9, 0xcd, 0x30, 0x8d, 0xc6, 0x19, 0x58,
	0x9b, 0x56, 0x12, 0x15, 0x21, 0xd7, 0x0d, 0x03, 0xf1, 0x7a, 0x05, 0x8a, 0xc9, 0xeb, 0xa6, 0x81,
	0x76, 0xa0, 0x34, 0x7b, 0xd9, 0xcc, 0x34, 0x9e, 0xc2, 0xde, 0xca, 0x66, 0x22, 0x80, 0xc2, 0x40,
	0x8c, 0xb8, 0x6b, 0x6e, 0x09, 0x7e, 0x8b, 0xba, 0x9e, 0x43, 0x38, 0x75, 0x4d, 0x03, 0x95, 0x61,
	0xfb, 0x92, 0x04, 0xe4, 0x86, 0xba, 0x66, 0xa6, 0xf1, 0xbb, 0x01, 0x07, 0xeb, 0x6a, 0x86, 0x0e,
	0x16, 0x27, 0xa6, 0x17, 0x75, 0x02, 0x73, 0x0b, 0x1d, 0xc2, 0xfe, 0x22, 0xda, 0x0d, 0x79, 0x27,
	0x30, 0x0d, 0x64, 0x2d, 0xbb, 0x69, 0xbf, 0xf6, 0x18, 0x67, 0x66, 0x06, 0x3d, 0x84, 0xa3, 0x45,
	0x4d, 0x2b, 0xa4, 0xac, 0x1b, 0x72, 0x4d, 0xc8, 0xae, 0xbe, 0x74, 0xc1, 0xcd, 0xdc, 0x2a, 0xfa,
	0x82, 0x9b, 0xf9, 0xe6, 0x1f, 0x59, 0x30, 0x97, 0x4b, 0x8c, 0x30, 0x54, 0xcf, 0x63, 0x4a, 0x38,
	0x5d, 0xd1, 0x1c, 0x6f, 0xfa, 0x5d, 0xa0, 0x7e, 0x50, 0xd5, 0xaa, 0x5a, 0xaf, 0x65, 0x4c, 0x59,
	0x14, 0x06, 0x8c, 0xda, 0x5b, 0xa8, 0x07, 0xfb, 0x17, 0x94, 0xdf, 0xa3, 0x43, 0x0c, 0xd5, 0x16,
	0xf5, 0xe9, 0xbd, 0x06, 0xf9, 0x0d, 0xbc, 0xdb, 0x17, 0x2b, 0x74, 0xbf, 0x79, 0xf7, 0x27, 0xf7,
	0x98, 0xf7, 0xb0, 0x20, 0x15, 0x9f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x01, 0x26, 0xc3,
	0x50, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersistentVolumeClient is the client API for PersistentVolume service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersistentVolumeClient interface {
	CreatePersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error)
	GetPersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error)
	DeletePersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error)
	PatchPersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error)
	PutPersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type persistentVolumeClient struct {
	cc *grpc.ClientConn
}

func NewPersistentVolumeClient(cc *grpc.ClientConn) PersistentVolumeClient {
	return &persistentVolumeClient{cc}
}

func (c *persistentVolumeClient) CreatePersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.PersistentVolume/CreatePersistentVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistentVolumeClient) GetPersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.PersistentVolume/GetPersistentVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistentVolumeClient) DeletePersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.PersistentVolume/DeletePersistentVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistentVolumeClient) PatchPersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.PersistentVolume/PatchPersistentVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistentVolumeClient) PutPersistentVolume(ctx context.Context, in *PersistentVolumeService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.PersistentVolume/PutPersistentVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistentVolumeServer is the server API for PersistentVolume service.
type PersistentVolumeServer interface {
	CreatePersistentVolume(context.Context, *PersistentVolumeService) (*ServiceResponse, error)
	GetPersistentVolume(context.Context, *PersistentVolumeService) (*ServiceResponse, error)
	DeletePersistentVolume(context.Context, *PersistentVolumeService) (*ServiceResponse, error)
	PatchPersistentVolume(context.Context, *PersistentVolumeService) (*ServiceResponse, error)
	PutPersistentVolume(context.Context, *PersistentVolumeService) (*ServiceResponse, error)
}

// UnimplementedPersistentVolumeServer can be embedded to have forward compatible implementations.
type UnimplementedPersistentVolumeServer struct {
}

func (*UnimplementedPersistentVolumeServer) CreatePersistentVolume(ctx context.Context, req *PersistentVolumeService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePersistentVolume not implemented")
}
func (*UnimplementedPersistentVolumeServer) GetPersistentVolume(ctx context.Context, req *PersistentVolumeService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersistentVolume not implemented")
}
func (*UnimplementedPersistentVolumeServer) DeletePersistentVolume(ctx context.Context, req *PersistentVolumeService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePersistentVolume not implemented")
}
func (*UnimplementedPersistentVolumeServer) PatchPersistentVolume(ctx context.Context, req *PersistentVolumeService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchPersistentVolume not implemented")
}
func (*UnimplementedPersistentVolumeServer) PutPersistentVolume(ctx context.Context, req *PersistentVolumeService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPersistentVolume not implemented")
}

func RegisterPersistentVolumeServer(s *grpc.Server, srv PersistentVolumeServer) {
	s.RegisterService(&_PersistentVolume_serviceDesc, srv)
}

func _PersistentVolume_CreatePersistentVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistentVolumeService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistentVolumeServer).CreatePersistentVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PersistentVolume/CreatePersistentVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistentVolumeServer).CreatePersistentVolume(ctx, req.(*PersistentVolumeService))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistentVolume_GetPersistentVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistentVolumeService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistentVolumeServer).GetPersistentVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PersistentVolume/GetPersistentVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistentVolumeServer).GetPersistentVolume(ctx, req.(*PersistentVolumeService))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistentVolume_DeletePersistentVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistentVolumeService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistentVolumeServer).DeletePersistentVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PersistentVolume/DeletePersistentVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistentVolumeServer).DeletePersistentVolume(ctx, req.(*PersistentVolumeService))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistentVolume_PatchPersistentVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistentVolumeService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistentVolumeServer).PatchPersistentVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PersistentVolume/PatchPersistentVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistentVolumeServer).PatchPersistentVolume(ctx, req.(*PersistentVolumeService))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistentVolume_PutPersistentVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistentVolumeService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistentVolumeServer).PutPersistentVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PersistentVolume/PutPersistentVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistentVolumeServer).PutPersistentVolume(ctx, req.(*PersistentVolumeService))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersistentVolume_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PersistentVolume",
	HandlerType: (*PersistentVolumeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePersistentVolume",
			Handler:    _PersistentVolume_CreatePersistentVolume_Handler,
		},
		{
			MethodName: "GetPersistentVolume",
			Handler:    _PersistentVolume_GetPersistentVolume_Handler,
		},
		{
			MethodName: "DeletePersistentVolume",
			Handler:    _PersistentVolume_DeletePersistentVolume_Handler,
		},
		{
			MethodName: "PatchPersistentVolume",
			Handler:    _PersistentVolume_PatchPersistentVolume_Handler,
		},
		{
			MethodName: "PutPersistentVolume",
			Handler:    _PersistentVolume_PutPersistentVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persistentvolume.proto",
}
