// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceResponse struct {
	Error                string         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Status               *ServiceStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServiceResponse) Reset()         { *m = ServiceResponse{} }
func (m *ServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceResponse) ProtoMessage()    {}
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceResponse.Unmarshal(m, b)
}
func (m *ServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceResponse.Marshal(b, m, deterministic)
}
func (m *ServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceResponse.Merge(m, src)
}
func (m *ServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceResponse.Size(m)
}
func (m *ServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceResponse proto.InternalMessageInfo

func (m *ServiceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ServiceResponse) GetStatus() *ServiceStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ServiceStatus struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StatusIndividual     []string `protobuf:"bytes,4,rep,name=status_individual,json=statusIndividual,proto3" json:"status_individual,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceStatus) Reset()         { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()    {}
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatus.Unmarshal(m, b)
}
func (m *ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatus.Merge(m, src)
}
func (m *ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_ServiceStatus.Size(m)
}
func (m *ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatus proto.InternalMessageInfo

func (m *ServiceStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceStatus) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ServiceStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceStatus) GetStatusIndividual() []string {
	if m != nil {
		return m.StatusIndividual
	}
	return nil
}

func (m *ServiceStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ServiceStatus) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type NameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameRequest) Reset()         { *m = NameRequest{} }
func (m *NameRequest) String() string { return proto.CompactTextString(m) }
func (*NameRequest) ProtoMessage()    {}
func (*NameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *NameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameRequest.Unmarshal(m, b)
}
func (m *NameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameRequest.Marshal(b, m, deterministic)
}
func (m *NameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRequest.Merge(m, src)
}
func (m *NameRequest) XXX_Size() int {
	return xxx_messageInfo_NameRequest.Size(m)
}
func (m *NameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NameRequest proto.InternalMessageInfo

func (m *NameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceResponse)(nil), "proto.ServiceResponse")
	proto.RegisterType((*ServiceStatus)(nil), "proto.ServiceStatus")
	proto.RegisterType((*NameRequest)(nil), "proto.NameRequest")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x49, 0x77, 0x5b, 0xd8, 0x59, 0xd6, 0x3f, 0xc3, 0x22, 0xb9, 0x08, 0xb5, 0x27, 0x41,
	0xe9, 0x41, 0x3f, 0x45, 0x2f, 0x1e, 0x52, 0x3c, 0x97, 0x68, 0xe6, 0x10, 0xd0, 0xa4, 0x26, 0x69,
	0xbf, 0x96, 0x5f, 0xd1, 0x98, 0x84, 0x8a, 0xa7, 0xce, 0xfb, 0xbd, 0xe9, 0x7b, 0x13, 0x38, 0x79,
	0x72, 0xab, 0x7e, 0xa7, 0x7e, 0x76, 0x36, 0x58, 0xac, 0xd3, 0xa7, 0x7b, 0x85, 0xcb, 0x31, 0x73,
	0x41, 0x7e, 0xb6, 0xc6, 0x13, 0x9e, 0xa1, 0x26, 0xe7, 0xac, 0xe3, 0xac, 0x65, 0xf7, 0x07, 0x91,
	0x05, 0x3e, 0x42, 0xe3, 0x83, 0x0c, 0x8b, 0xe7, 0x55, 0xc4, 0xc7, 0xa7, 0x73, 0xce, 0xe9, 0xcb,
	0xdf, 0x63, 0xf2, 0x44, 0xd9, 0xe9, 0xbe, 0x19, 0x9c, 0xfe, 0x39, 0x78, 0x01, 0x95, 0x56, 0x25,
	0x32, 0x4e, 0x78, 0x0b, 0x50, 0x0e, 0x9a, 0x22, 0xaf, 0x12, 0x3f, 0x14, 0x32, 0x28, 0x44, 0xd8,
	0x1b, 0xf9, 0x49, 0x7c, 0x97, 0x8c, 0x34, 0xe3, 0x03, 0x5c, 0xe7, 0xf8, 0x49, 0x1b, 0xa5, 0x57,
	0xad, 0x16, 0xf9, 0xc1, 0xf7, 0xed, 0x2e, 0x2e, 0x5c, 0x65, 0x63, 0xd8, 0x38, 0xde, 0x6c, 0xf7,
	0xd6, 0x29, 0xa2, 0xa8, 0x5f, 0xee, 0x48, 0x7a, 0x6b, 0x78, 0x93, 0x79, 0x56, 0xdd, 0x1d, 0x1c,
	0x5f, 0x62, 0x89, 0xa0, 0xaf, 0x85, 0x7c, 0xd8, 0xfa, 0xd9, 0x5f, 0xff, 0x5b, 0x93, 0x5e, 0xfc,
	0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x62, 0x35, 0x2e, 0x75, 0x4a, 0x01, 0x00, 0x00,
}
