// Code generated by protoc-gen-go. DO NOT EDIT.
// source: virtualservice.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VirtualService struct {
	ProjectId            string        `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId            string        `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version              string        `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	ServiceType          string        `protobuf:"bytes,5,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ServiceSubType       string        `protobuf:"bytes,6,opt,name=service_sub_type,json=serviceSubType,proto3" json:"service_sub_type,omitempty"`
	Namespace            string        `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Token                string        `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	CompanyId            string        `protobuf:"bytes,9,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ServiceAttributes    *VSAttributes `protobuf:"bytes,10,opt,name=service_attributes,json=serviceAttributes,proto3" json:"service_attributes,omitempty"`
	Status               string        `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VirtualService) Reset()         { *m = VirtualService{} }
func (m *VirtualService) String() string { return proto.CompactTextString(m) }
func (*VirtualService) ProtoMessage()    {}
func (*VirtualService) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{0}
}

func (m *VirtualService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualService.Unmarshal(m, b)
}
func (m *VirtualService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualService.Marshal(b, m, deterministic)
}
func (m *VirtualService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualService.Merge(m, src)
}
func (m *VirtualService) XXX_Size() int {
	return xxx_messageInfo_VirtualService.Size(m)
}
func (m *VirtualService) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualService.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualService proto.InternalMessageInfo

func (m *VirtualService) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *VirtualService) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *VirtualService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualService) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VirtualService) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *VirtualService) GetServiceSubType() string {
	if m != nil {
		return m.ServiceSubType
	}
	return ""
}

func (m *VirtualService) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *VirtualService) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VirtualService) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *VirtualService) GetServiceAttributes() *VSAttributes {
	if m != nil {
		return m.ServiceAttributes
	}
	return nil
}

func (m *VirtualService) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type VSAttributes struct {
	Hosts                []string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Gateways             []string `protobuf:"bytes,2,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Http                 []*Http  `protobuf:"bytes,3,rep,name=http,proto3" json:"http,omitempty"`
	Tls                  []*Tls   `protobuf:"bytes,4,rep,name=tls,proto3" json:"tls,omitempty"`
	Tcp                  []*Tcp   `protobuf:"bytes,5,rep,name=tcp,proto3" json:"tcp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VSAttributes) Reset()         { *m = VSAttributes{} }
func (m *VSAttributes) String() string { return proto.CompactTextString(m) }
func (*VSAttributes) ProtoMessage()    {}
func (*VSAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{1}
}

func (m *VSAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VSAttributes.Unmarshal(m, b)
}
func (m *VSAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VSAttributes.Marshal(b, m, deterministic)
}
func (m *VSAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSAttributes.Merge(m, src)
}
func (m *VSAttributes) XXX_Size() int {
	return xxx_messageInfo_VSAttributes.Size(m)
}
func (m *VSAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_VSAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_VSAttributes proto.InternalMessageInfo

func (m *VSAttributes) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *VSAttributes) GetGateways() []string {
	if m != nil {
		return m.Gateways
	}
	return nil
}

func (m *VSAttributes) GetHttp() []*Http {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *VSAttributes) GetTls() []*Tls {
	if m != nil {
		return m.Tls
	}
	return nil
}

func (m *VSAttributes) GetTcp() []*Tcp {
	if m != nil {
		return m.Tcp
	}
	return nil
}

type Http struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MatchRequest         []*HttpMatchRequest `protobuf:"bytes,2,rep,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	HttpRoute            []*HttpRoute        `protobuf:"bytes,3,rep,name=http_route,json=httpRoute,proto3" json:"http_route,omitempty"`
	HttpRedirect         *HttpRedirect       `protobuf:"bytes,4,opt,name=http_redirect,json=httpRedirect,proto3" json:"http_redirect,omitempty"`
	HttpRewrite          *HttpRewrite        `protobuf:"bytes,5,opt,name=http_rewrite,json=httpRewrite,proto3" json:"http_rewrite,omitempty"`
	Timeout              int64               `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retry                *HttpRetry          `protobuf:"bytes,7,opt,name=retry,proto3" json:"retry,omitempty"`
	FaultInjection       *HttpFaultInjection `protobuf:"bytes,8,opt,name=fault_injection,json=faultInjection,proto3" json:"fault_injection,omitempty"`
	CorsPolicy           *HttpCorsPolicy     `protobuf:"bytes,9,opt,name=cors_policy,json=corsPolicy,proto3" json:"cors_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Http) Reset()         { *m = Http{} }
func (m *Http) String() string { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()    {}
func (*Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{2}
}

func (m *Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http.Unmarshal(m, b)
}
func (m *Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http.Marshal(b, m, deterministic)
}
func (m *Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http.Merge(m, src)
}
func (m *Http) XXX_Size() int {
	return xxx_messageInfo_Http.Size(m)
}
func (m *Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Http proto.InternalMessageInfo

func (m *Http) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Http) GetMatchRequest() []*HttpMatchRequest {
	if m != nil {
		return m.MatchRequest
	}
	return nil
}

func (m *Http) GetHttpRoute() []*HttpRoute {
	if m != nil {
		return m.HttpRoute
	}
	return nil
}

func (m *Http) GetHttpRedirect() *HttpRedirect {
	if m != nil {
		return m.HttpRedirect
	}
	return nil
}

func (m *Http) GetHttpRewrite() *HttpRewrite {
	if m != nil {
		return m.HttpRewrite
	}
	return nil
}

func (m *Http) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Http) GetRetry() *HttpRetry {
	if m != nil {
		return m.Retry
	}
	return nil
}

func (m *Http) GetFaultInjection() *HttpFaultInjection {
	if m != nil {
		return m.FaultInjection
	}
	return nil
}

func (m *Http) GetCorsPolicy() *HttpCorsPolicy {
	if m != nil {
		return m.CorsPolicy
	}
	return nil
}

type HttpMatchRequest struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri                  *HttpMatch `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Scheme               *HttpMatch `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Method               *HttpMatch `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Authority            *HttpMatch `protobuf:"bytes,5,opt,name=authority,proto3" json:"authority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HttpMatchRequest) Reset()         { *m = HttpMatchRequest{} }
func (m *HttpMatchRequest) String() string { return proto.CompactTextString(m) }
func (*HttpMatchRequest) ProtoMessage()    {}
func (*HttpMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{3}
}

func (m *HttpMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpMatchRequest.Unmarshal(m, b)
}
func (m *HttpMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpMatchRequest.Marshal(b, m, deterministic)
}
func (m *HttpMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpMatchRequest.Merge(m, src)
}
func (m *HttpMatchRequest) XXX_Size() int {
	return xxx_messageInfo_HttpMatchRequest.Size(m)
}
func (m *HttpMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpMatchRequest proto.InternalMessageInfo

func (m *HttpMatchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HttpMatchRequest) GetUri() *HttpMatch {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (m *HttpMatchRequest) GetScheme() *HttpMatch {
	if m != nil {
		return m.Scheme
	}
	return nil
}

func (m *HttpMatchRequest) GetMethod() *HttpMatch {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *HttpMatchRequest) GetAuthority() *HttpMatch {
	if m != nil {
		return m.Authority
	}
	return nil
}

type HttpMatch struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpMatch) Reset()         { *m = HttpMatch{} }
func (m *HttpMatch) String() string { return proto.CompactTextString(m) }
func (*HttpMatch) ProtoMessage()    {}
func (*HttpMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{4}
}

func (m *HttpMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpMatch.Unmarshal(m, b)
}
func (m *HttpMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpMatch.Marshal(b, m, deterministic)
}
func (m *HttpMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpMatch.Merge(m, src)
}
func (m *HttpMatch) XXX_Size() int {
	return xxx_messageInfo_HttpMatch.Size(m)
}
func (m *HttpMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpMatch.DiscardUnknown(m)
}

var xxx_messageInfo_HttpMatch proto.InternalMessageInfo

func (m *HttpMatch) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HttpMatch) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HttpRoute struct {
	Routes               *HttpRouteDestination `protobuf:"bytes,1,opt,name=routes,proto3" json:"routes,omitempty"`
	Weight               int32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HttpRoute) Reset()         { *m = HttpRoute{} }
func (m *HttpRoute) String() string { return proto.CompactTextString(m) }
func (*HttpRoute) ProtoMessage()    {}
func (*HttpRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{5}
}

func (m *HttpRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRoute.Unmarshal(m, b)
}
func (m *HttpRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRoute.Marshal(b, m, deterministic)
}
func (m *HttpRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRoute.Merge(m, src)
}
func (m *HttpRoute) XXX_Size() int {
	return xxx_messageInfo_HttpRoute.Size(m)
}
func (m *HttpRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRoute.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRoute proto.InternalMessageInfo

func (m *HttpRoute) GetRoutes() *HttpRouteDestination {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *HttpRoute) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type HttpRouteDestination struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Subset               string   `protobuf:"bytes,3,opt,name=subset,proto3" json:"subset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpRouteDestination) Reset()         { *m = HttpRouteDestination{} }
func (m *HttpRouteDestination) String() string { return proto.CompactTextString(m) }
func (*HttpRouteDestination) ProtoMessage()    {}
func (*HttpRouteDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{6}
}

func (m *HttpRouteDestination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRouteDestination.Unmarshal(m, b)
}
func (m *HttpRouteDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRouteDestination.Marshal(b, m, deterministic)
}
func (m *HttpRouteDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRouteDestination.Merge(m, src)
}
func (m *HttpRouteDestination) XXX_Size() int {
	return xxx_messageInfo_HttpRouteDestination.Size(m)
}
func (m *HttpRouteDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRouteDestination.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRouteDestination proto.InternalMessageInfo

func (m *HttpRouteDestination) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *HttpRouteDestination) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HttpRouteDestination) GetSubset() string {
	if m != nil {
		return m.Subset
	}
	return ""
}

type HttpRedirect struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	RedirectCode         int32    `protobuf:"varint,3,opt,name=redirect_code,json=redirectCode,proto3" json:"redirect_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpRedirect) Reset()         { *m = HttpRedirect{} }
func (m *HttpRedirect) String() string { return proto.CompactTextString(m) }
func (*HttpRedirect) ProtoMessage()    {}
func (*HttpRedirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{7}
}

func (m *HttpRedirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRedirect.Unmarshal(m, b)
}
func (m *HttpRedirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRedirect.Marshal(b, m, deterministic)
}
func (m *HttpRedirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRedirect.Merge(m, src)
}
func (m *HttpRedirect) XXX_Size() int {
	return xxx_messageInfo_HttpRedirect.Size(m)
}
func (m *HttpRedirect) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRedirect.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRedirect proto.InternalMessageInfo

func (m *HttpRedirect) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HttpRedirect) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *HttpRedirect) GetRedirectCode() int32 {
	if m != nil {
		return m.RedirectCode
	}
	return 0
}

type HttpRewrite struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpRewrite) Reset()         { *m = HttpRewrite{} }
func (m *HttpRewrite) String() string { return proto.CompactTextString(m) }
func (*HttpRewrite) ProtoMessage()    {}
func (*HttpRewrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{8}
}

func (m *HttpRewrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRewrite.Unmarshal(m, b)
}
func (m *HttpRewrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRewrite.Marshal(b, m, deterministic)
}
func (m *HttpRewrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRewrite.Merge(m, src)
}
func (m *HttpRewrite) XXX_Size() int {
	return xxx_messageInfo_HttpRewrite.Size(m)
}
func (m *HttpRewrite) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRewrite.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRewrite proto.InternalMessageInfo

func (m *HttpRewrite) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HttpRewrite) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type HttpRetry struct {
	TotalAttempts        int32    `protobuf:"varint,1,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	PerTryTimeout        int64    `protobuf:"varint,2,opt,name=per_try_timeout,json=perTryTimeout,proto3" json:"per_try_timeout,omitempty"`
	RetryOn              string   `protobuf:"bytes,3,opt,name=retry_on,json=retryOn,proto3" json:"retry_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpRetry) Reset()         { *m = HttpRetry{} }
func (m *HttpRetry) String() string { return proto.CompactTextString(m) }
func (*HttpRetry) ProtoMessage()    {}
func (*HttpRetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{9}
}

func (m *HttpRetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRetry.Unmarshal(m, b)
}
func (m *HttpRetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRetry.Marshal(b, m, deterministic)
}
func (m *HttpRetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRetry.Merge(m, src)
}
func (m *HttpRetry) XXX_Size() int {
	return xxx_messageInfo_HttpRetry.Size(m)
}
func (m *HttpRetry) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRetry.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRetry proto.InternalMessageInfo

func (m *HttpRetry) GetTotalAttempts() int32 {
	if m != nil {
		return m.TotalAttempts
	}
	return 0
}

func (m *HttpRetry) GetPerTryTimeout() int64 {
	if m != nil {
		return m.PerTryTimeout
	}
	return 0
}

func (m *HttpRetry) GetRetryOn() string {
	if m != nil {
		return m.RetryOn
	}
	return ""
}

type HttpFaultInjection struct {
	DelayType            string   `protobuf:"bytes,1,opt,name=delay_type,json=delayType,proto3" json:"delay_type,omitempty"`
	DelayValue           int32    `protobuf:"varint,2,opt,name=delay_value,json=delayValue,proto3" json:"delay_value,omitempty"`
	FaultPercentage      float32  `protobuf:"fixed32,3,opt,name=fault_percentage,json=faultPercentage,proto3" json:"fault_percentage,omitempty"`
	AbortErrorValue      string   `protobuf:"bytes,4,opt,name=abort_error_value,json=abortErrorValue,proto3" json:"abort_error_value,omitempty"`
	AbortPercentage      string   `protobuf:"bytes,5,opt,name=abort_percentage,json=abortPercentage,proto3" json:"abort_percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpFaultInjection) Reset()         { *m = HttpFaultInjection{} }
func (m *HttpFaultInjection) String() string { return proto.CompactTextString(m) }
func (*HttpFaultInjection) ProtoMessage()    {}
func (*HttpFaultInjection) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{10}
}

func (m *HttpFaultInjection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpFaultInjection.Unmarshal(m, b)
}
func (m *HttpFaultInjection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpFaultInjection.Marshal(b, m, deterministic)
}
func (m *HttpFaultInjection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpFaultInjection.Merge(m, src)
}
func (m *HttpFaultInjection) XXX_Size() int {
	return xxx_messageInfo_HttpFaultInjection.Size(m)
}
func (m *HttpFaultInjection) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpFaultInjection.DiscardUnknown(m)
}

var xxx_messageInfo_HttpFaultInjection proto.InternalMessageInfo

func (m *HttpFaultInjection) GetDelayType() string {
	if m != nil {
		return m.DelayType
	}
	return ""
}

func (m *HttpFaultInjection) GetDelayValue() int32 {
	if m != nil {
		return m.DelayValue
	}
	return 0
}

func (m *HttpFaultInjection) GetFaultPercentage() float32 {
	if m != nil {
		return m.FaultPercentage
	}
	return 0
}

func (m *HttpFaultInjection) GetAbortErrorValue() string {
	if m != nil {
		return m.AbortErrorValue
	}
	return ""
}

func (m *HttpFaultInjection) GetAbortPercentage() string {
	if m != nil {
		return m.AbortPercentage
	}
	return ""
}

type HttpCorsPolicy struct {
	AllowOrigin          []string `protobuf:"bytes,1,rep,name=allow_origin,json=allowOrigin,proto3" json:"allow_origin,omitempty"`
	AllMethod            []string `protobuf:"bytes,2,rep,name=all_method,json=allMethod,proto3" json:"all_method,omitempty"`
	AllowHeaders         []string `protobuf:"bytes,3,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	ExposeHeaders        []string `protobuf:"bytes,4,rep,name=expose_headers,json=exposeHeaders,proto3" json:"expose_headers,omitempty"`
	MaxAge               int64    `protobuf:"varint,5,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	AllowCredentials     bool     `protobuf:"varint,6,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpCorsPolicy) Reset()         { *m = HttpCorsPolicy{} }
func (m *HttpCorsPolicy) String() string { return proto.CompactTextString(m) }
func (*HttpCorsPolicy) ProtoMessage()    {}
func (*HttpCorsPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{11}
}

func (m *HttpCorsPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpCorsPolicy.Unmarshal(m, b)
}
func (m *HttpCorsPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpCorsPolicy.Marshal(b, m, deterministic)
}
func (m *HttpCorsPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpCorsPolicy.Merge(m, src)
}
func (m *HttpCorsPolicy) XXX_Size() int {
	return xxx_messageInfo_HttpCorsPolicy.Size(m)
}
func (m *HttpCorsPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpCorsPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_HttpCorsPolicy proto.InternalMessageInfo

func (m *HttpCorsPolicy) GetAllowOrigin() []string {
	if m != nil {
		return m.AllowOrigin
	}
	return nil
}

func (m *HttpCorsPolicy) GetAllMethod() []string {
	if m != nil {
		return m.AllMethod
	}
	return nil
}

func (m *HttpCorsPolicy) GetAllowHeaders() []string {
	if m != nil {
		return m.AllowHeaders
	}
	return nil
}

func (m *HttpCorsPolicy) GetExposeHeaders() []string {
	if m != nil {
		return m.ExposeHeaders
	}
	return nil
}

func (m *HttpCorsPolicy) GetMaxAge() int64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *HttpCorsPolicy) GetAllowCredentials() bool {
	if m != nil {
		return m.AllowCredentials
	}
	return false
}

type Tls struct {
	Match                []*TlsMatchAttribute `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	Routes               []*TlsRoute          `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Tls) Reset()         { *m = Tls{} }
func (m *Tls) String() string { return proto.CompactTextString(m) }
func (*Tls) ProtoMessage()    {}
func (*Tls) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{12}
}

func (m *Tls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tls.Unmarshal(m, b)
}
func (m *Tls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tls.Marshal(b, m, deterministic)
}
func (m *Tls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tls.Merge(m, src)
}
func (m *Tls) XXX_Size() int {
	return xxx_messageInfo_Tls.Size(m)
}
func (m *Tls) XXX_DiscardUnknown() {
	xxx_messageInfo_Tls.DiscardUnknown(m)
}

var xxx_messageInfo_Tls proto.InternalMessageInfo

func (m *Tls) GetMatch() []*TlsMatchAttribute {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *Tls) GetRoutes() []*TlsRoute {
	if m != nil {
		return m.Routes
	}
	return nil
}

type TlsMatchAttribute struct {
	SniHosts             []string `protobuf:"bytes,1,rep,name=sni_hosts,json=sniHosts,proto3" json:"sni_hosts,omitempty"`
	DestinationSubnets   []string `protobuf:"bytes,2,rep,name=destination_subnets,json=destinationSubnets,proto3" json:"destination_subnets,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	SourceSubnet         string   `protobuf:"bytes,4,opt,name=source_subnet,json=sourceSubnet,proto3" json:"source_subnet,omitempty"`
	Gateways             []string `protobuf:"bytes,5,rep,name=gateways,proto3" json:"gateways,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TlsMatchAttribute) Reset()         { *m = TlsMatchAttribute{} }
func (m *TlsMatchAttribute) String() string { return proto.CompactTextString(m) }
func (*TlsMatchAttribute) ProtoMessage()    {}
func (*TlsMatchAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{13}
}

func (m *TlsMatchAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TlsMatchAttribute.Unmarshal(m, b)
}
func (m *TlsMatchAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TlsMatchAttribute.Marshal(b, m, deterministic)
}
func (m *TlsMatchAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TlsMatchAttribute.Merge(m, src)
}
func (m *TlsMatchAttribute) XXX_Size() int {
	return xxx_messageInfo_TlsMatchAttribute.Size(m)
}
func (m *TlsMatchAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_TlsMatchAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_TlsMatchAttribute proto.InternalMessageInfo

func (m *TlsMatchAttribute) GetSniHosts() []string {
	if m != nil {
		return m.SniHosts
	}
	return nil
}

func (m *TlsMatchAttribute) GetDestinationSubnets() []string {
	if m != nil {
		return m.DestinationSubnets
	}
	return nil
}

func (m *TlsMatchAttribute) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *TlsMatchAttribute) GetSourceSubnet() string {
	if m != nil {
		return m.SourceSubnet
	}
	return ""
}

func (m *TlsMatchAttribute) GetGateways() []string {
	if m != nil {
		return m.Gateways
	}
	return nil
}

type TlsRoute struct {
	RouteDestination     *RouteDestination `protobuf:"bytes,1,opt,name=route_destination,json=routeDestination,proto3" json:"route_destination,omitempty"`
	Weight               int32             `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TlsRoute) Reset()         { *m = TlsRoute{} }
func (m *TlsRoute) String() string { return proto.CompactTextString(m) }
func (*TlsRoute) ProtoMessage()    {}
func (*TlsRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{14}
}

func (m *TlsRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TlsRoute.Unmarshal(m, b)
}
func (m *TlsRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TlsRoute.Marshal(b, m, deterministic)
}
func (m *TlsRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TlsRoute.Merge(m, src)
}
func (m *TlsRoute) XXX_Size() int {
	return xxx_messageInfo_TlsRoute.Size(m)
}
func (m *TlsRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_TlsRoute.DiscardUnknown(m)
}

var xxx_messageInfo_TlsRoute proto.InternalMessageInfo

func (m *TlsRoute) GetRouteDestination() *RouteDestination {
	if m != nil {
		return m.RouteDestination
	}
	return nil
}

func (m *TlsRoute) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type RouteDestination struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Subnet               string   `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteDestination) Reset()         { *m = RouteDestination{} }
func (m *RouteDestination) String() string { return proto.CompactTextString(m) }
func (*RouteDestination) ProtoMessage()    {}
func (*RouteDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{15}
}

func (m *RouteDestination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteDestination.Unmarshal(m, b)
}
func (m *RouteDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteDestination.Marshal(b, m, deterministic)
}
func (m *RouteDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteDestination.Merge(m, src)
}
func (m *RouteDestination) XXX_Size() int {
	return xxx_messageInfo_RouteDestination.Size(m)
}
func (m *RouteDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteDestination.DiscardUnknown(m)
}

var xxx_messageInfo_RouteDestination proto.InternalMessageInfo

func (m *RouteDestination) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RouteDestination) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

func (m *RouteDestination) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Tcp struct {
	Match                []*TcpMatchRequest `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	Routes               []*TcpRoutes       `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Tcp) Reset()         { *m = Tcp{} }
func (m *Tcp) String() string { return proto.CompactTextString(m) }
func (*Tcp) ProtoMessage()    {}
func (*Tcp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{16}
}

func (m *Tcp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tcp.Unmarshal(m, b)
}
func (m *Tcp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tcp.Marshal(b, m, deterministic)
}
func (m *Tcp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tcp.Merge(m, src)
}
func (m *Tcp) XXX_Size() int {
	return xxx_messageInfo_Tcp.Size(m)
}
func (m *Tcp) XXX_DiscardUnknown() {
	xxx_messageInfo_Tcp.DiscardUnknown(m)
}

var xxx_messageInfo_Tcp proto.InternalMessageInfo

func (m *Tcp) GetMatch() []*TcpMatchRequest {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *Tcp) GetRoutes() []*TcpRoutes {
	if m != nil {
		return m.Routes
	}
	return nil
}

type TcpMatchRequest struct {
	DestinationSubnets   []string          `protobuf:"bytes,1,rep,name=destination_subnets,json=destinationSubnets,proto3" json:"destination_subnets,omitempty"`
	Port                 int32             `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	SourceSubnet         string            `protobuf:"bytes,3,opt,name=source_subnet,json=sourceSubnet,proto3" json:"source_subnet,omitempty"`
	SourceLabels         map[string]string `protobuf:"bytes,4,rep,name=Source_labels,json=SourceLabels,proto3" json:"Source_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Gateways             []string          `protobuf:"bytes,5,rep,name=gateways,proto3" json:"gateways,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TcpMatchRequest) Reset()         { *m = TcpMatchRequest{} }
func (m *TcpMatchRequest) String() string { return proto.CompactTextString(m) }
func (*TcpMatchRequest) ProtoMessage()    {}
func (*TcpMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{17}
}

func (m *TcpMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpMatchRequest.Unmarshal(m, b)
}
func (m *TcpMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpMatchRequest.Marshal(b, m, deterministic)
}
func (m *TcpMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpMatchRequest.Merge(m, src)
}
func (m *TcpMatchRequest) XXX_Size() int {
	return xxx_messageInfo_TcpMatchRequest.Size(m)
}
func (m *TcpMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TcpMatchRequest proto.InternalMessageInfo

func (m *TcpMatchRequest) GetDestinationSubnets() []string {
	if m != nil {
		return m.DestinationSubnets
	}
	return nil
}

func (m *TcpMatchRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *TcpMatchRequest) GetSourceSubnet() string {
	if m != nil {
		return m.SourceSubnet
	}
	return ""
}

func (m *TcpMatchRequest) GetSourceLabels() map[string]string {
	if m != nil {
		return m.SourceLabels
	}
	return nil
}

func (m *TcpMatchRequest) GetGateways() []string {
	if m != nil {
		return m.Gateways
	}
	return nil
}

type SourceLabel struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceLabel) Reset()         { *m = SourceLabel{} }
func (m *SourceLabel) String() string { return proto.CompactTextString(m) }
func (*SourceLabel) ProtoMessage()    {}
func (*SourceLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{18}
}

func (m *SourceLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceLabel.Unmarshal(m, b)
}
func (m *SourceLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceLabel.Marshal(b, m, deterministic)
}
func (m *SourceLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceLabel.Merge(m, src)
}
func (m *SourceLabel) XXX_Size() int {
	return xxx_messageInfo_SourceLabel.Size(m)
}
func (m *SourceLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceLabel.DiscardUnknown(m)
}

var xxx_messageInfo_SourceLabel proto.InternalMessageInfo

func (m *SourceLabel) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type TcpRoutes struct {
	Destination          *RouteDestination `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Weight               int32             `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TcpRoutes) Reset()         { *m = TcpRoutes{} }
func (m *TcpRoutes) String() string { return proto.CompactTextString(m) }
func (*TcpRoutes) ProtoMessage()    {}
func (*TcpRoutes) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1afc8130a39a5ad, []int{19}
}

func (m *TcpRoutes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpRoutes.Unmarshal(m, b)
}
func (m *TcpRoutes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpRoutes.Marshal(b, m, deterministic)
}
func (m *TcpRoutes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpRoutes.Merge(m, src)
}
func (m *TcpRoutes) XXX_Size() int {
	return xxx_messageInfo_TcpRoutes.Size(m)
}
func (m *TcpRoutes) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpRoutes.DiscardUnknown(m)
}

var xxx_messageInfo_TcpRoutes proto.InternalMessageInfo

func (m *TcpRoutes) GetDestination() *RouteDestination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *TcpRoutes) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*VirtualService)(nil), "proto.VirtualService")
	proto.RegisterType((*VSAttributes)(nil), "proto.VSAttributes")
	proto.RegisterType((*Http)(nil), "proto.Http")
	proto.RegisterType((*HttpMatchRequest)(nil), "proto.HttpMatchRequest")
	proto.RegisterType((*HttpMatch)(nil), "proto.HttpMatch")
	proto.RegisterType((*HttpRoute)(nil), "proto.HttpRoute")
	proto.RegisterType((*HttpRouteDestination)(nil), "proto.HttpRouteDestination")
	proto.RegisterType((*HttpRedirect)(nil), "proto.HttpRedirect")
	proto.RegisterType((*HttpRewrite)(nil), "proto.HttpRewrite")
	proto.RegisterType((*HttpRetry)(nil), "proto.HttpRetry")
	proto.RegisterType((*HttpFaultInjection)(nil), "proto.HttpFaultInjection")
	proto.RegisterType((*HttpCorsPolicy)(nil), "proto.HttpCorsPolicy")
	proto.RegisterType((*Tls)(nil), "proto.Tls")
	proto.RegisterType((*TlsMatchAttribute)(nil), "proto.TlsMatchAttribute")
	proto.RegisterType((*TlsRoute)(nil), "proto.TlsRoute")
	proto.RegisterType((*RouteDestination)(nil), "proto.RouteDestination")
	proto.RegisterType((*Tcp)(nil), "proto.Tcp")
	proto.RegisterType((*TcpMatchRequest)(nil), "proto.TcpMatchRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.TcpMatchRequest.SourceLabelsEntry")
	proto.RegisterType((*SourceLabel)(nil), "proto.SourceLabel")
	proto.RegisterType((*TcpRoutes)(nil), "proto.TcpRoutes")
}

func init() { proto.RegisterFile("virtualservice.proto", fileDescriptor_b1afc8130a39a5ad) }

var fileDescriptor_b1afc8130a39a5ad = []byte{
	// 1342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xc6, 0x76, 0x9c, 0x78, 0xcf, 0xda, 0x89, 0x33, 0x0d, 0xad, 0x9b, 0x16, 0x15, 0x16, 0x01,
	0xe1, 0x47, 0xa9, 0xe4, 0xaa, 0xa8, 0x20, 0x10, 0x2a, 0x49, 0xdb, 0x54, 0x22, 0x6a, 0x34, 0x89,
	0x22, 0x6e, 0x60, 0xb5, 0x5e, 0x4f, 0xe3, 0xa5, 0xeb, 0xdd, 0x65, 0x77, 0x36, 0x89, 0x1f, 0x86,
	0x6b, 0xde, 0x00, 0xf1, 0x14, 0x5c, 0xf2, 0x04, 0xdc, 0x73, 0xcb, 0x25, 0x67, 0xce, 0xcc, 0xae,
	0xd7, 0x3f, 0x29, 0xa0, 0x70, 0xe5, 0x99, 0xef, 0x3b, 0x67, 0x76, 0xce, 0xff, 0x18, 0xb6, 0xce,
	0x83, 0x54, 0xe6, 0x5e, 0x98, 0x89, 0xf4, 0x3c, 0xf0, 0xc5, 0x6e, 0x92, 0xc6, 0x32, 0x66, 0x4d,
	0xfa, 0xd9, 0xee, 0xcc, 0xa0, 0xce, 0x5f, 0x75, 0x58, 0x3f, 0xd5, 0xe2, 0xc7, 0x9a, 0x60, 0x6f,
	0x01, 0x20, 0xf7, 0x83, 0xf0, 0xa5, 0x1b, 0x0c, 0x7b, 0xb5, 0xb7, 0x6b, 0x3b, 0x16, 0xb7, 0x0c,
	0xf2, 0x7c, 0xa8, 0x68, 0x73, 0x84, 0xa2, 0xeb, 0x9a, 0x36, 0x08, 0xd2, 0x0c, 0x56, 0x22, 0x6f,
	0x2c, 0x7a, 0x0d, 0x22, 0x68, 0xcd, 0x7a, 0xb0, 0x76, 0x2e, 0xd2, 0x2c, 0x88, 0xa3, 0xde, 0x0a,
	0xc1, 0xc5, 0x96, 0xbd, 0x03, 0xed, 0xe2, 0x30, 0x39, 0x49, 0x44, 0xaf, 0x49, 0xb4, 0x6d, 0xb0,
	0x13, 0x84, 0xd8, 0x0e, 0x74, 0x0b, 0x91, 0x2c, 0x1f, 0x68, 0xb1, 0x55, 0x12, 0x5b, 0x37, 0xf8,
	0x71, 0x3e, 0x20, 0xc9, 0xbb, 0x60, 0xa9, 0xcf, 0x65, 0x89, 0xe7, 0x8b, 0xde, 0x9a, 0xbe, 0x58,
	0x09, 0xb0, 0x2d, 0x68, 0xca, 0xf8, 0x95, 0x88, 0x7a, 0x2d, 0x62, 0xf4, 0x46, 0x59, 0xe3, 0xc7,
	0xe3, 0xc4, 0x8b, 0x26, 0xca, 0x1a, 0x4b, 0x2b, 0x19, 0x04, 0xad, 0xf9, 0x1a, 0x58, 0xf1, 0x71,
	0x4f, 0xca, 0x34, 0x18, 0xe4, 0x52, 0x64, 0x3d, 0x40, 0x31, 0xbb, 0x7f, 0x43, 0xbb, 0x70, 0xf7,
	0xf4, 0xf8, 0x71, 0x49, 0xf1, 0x4d, 0x23, 0x3e, 0x85, 0xd8, 0x4d, 0x58, 0xcd, 0xa4, 0x27, 0xf3,
	0xac, 0x67, 0xd3, 0xf1, 0x66, 0xe7, 0xfc, 0x54, 0x83, 0x76, 0x55, 0x57, 0xdd, 0x70, 0x14, 0x67,
	0x32, 0x43, 0x9f, 0x37, 0xd4, 0x0d, 0x69, 0xc3, 0xb6, 0xa1, 0x75, 0xe6, 0x49, 0x71, 0xe1, 0x4d,
	0x32, 0xf4, 0xb6, 0x22, 0xca, 0x3d, 0xbb, 0x07, 0x2b, 0x23, 0x29, 0x13, 0x74, 0x76, 0x03, 0x2f,
	0x64, 0x9b, 0x0b, 0x1d, 0x20, 0xc4, 0x89, 0x40, 0x97, 0x34, 0x64, 0x98, 0xa1, 0xd7, 0x15, 0x0f,
	0x86, 0x3f, 0x09, 0x33, 0xae, 0x60, 0x62, 0xfd, 0x04, 0x9d, 0x3e, 0xc3, 0xfa, 0x09, 0x57, 0xb0,
	0xf3, 0x6b, 0x03, 0x56, 0xd4, 0x51, 0x65, 0x48, 0x6b, 0x95, 0x90, 0x7e, 0x01, 0x9d, 0xb1, 0x27,
	0xfd, 0x91, 0x9b, 0x8a, 0x1f, 0x73, 0x91, 0x49, 0xba, 0x9a, 0xdd, 0xbf, 0x55, 0xb9, 0xc2, 0xa1,
	0xe2, 0xb9, 0xa6, 0x79, 0x7b, 0x5c, 0xd9, 0xb1, 0xfb, 0x00, 0xea, 0x7a, 0x6e, 0x1a, 0xa3, 0xe1,
	0xe6, 0xf6, 0xdd, 0xea, 0xed, 0x15, 0xce, 0xad, 0x51, 0xb1, 0x64, 0x8f, 0xa0, 0xa3, 0x15, 0xc4,
	0x30, 0x48, 0x31, 0x0f, 0x29, 0x8f, 0xa6, 0x21, 0x20, 0x1d, 0x43, 0xf1, 0xf6, 0xa8, 0xb2, 0x63,
	0x0f, 0xa1, 0x6d, 0x34, 0x2f, 0xd2, 0x40, 0xea, 0x0c, 0xb3, 0xfb, 0x6c, 0x46, 0x91, 0x18, 0x6e,
	0x8f, 0xa6, 0x1b, 0x95, 0xb2, 0x32, 0x18, 0x0b, 0xfc, 0x38, 0x25, 0x5b, 0x83, 0x17, 0x5b, 0xf6,
	0x3e, 0x34, 0x53, 0x21, 0xd3, 0x09, 0x65, 0xd8, 0xdc, 0xb5, 0x15, 0xce, 0x35, 0x8d, 0xa9, 0xb3,
	0xf1, 0xd2, 0xcb, 0x43, 0x2c, 0xa2, 0x48, 0x55, 0x8e, 0x4a, 0xfe, 0x16, 0x69, 0xdc, 0xae, 0x68,
	0x3c, 0x55, 0x12, 0xcf, 0x0b, 0x01, 0xbe, 0xfe, 0x72, 0x66, 0xcf, 0x3e, 0x05, 0xdb, 0x8f, 0xd3,
	0xcc, 0x4d, 0xe2, 0x30, 0xf0, 0x27, 0x94, 0x9e, 0x76, 0xff, 0xcd, 0x8a, 0xfe, 0x1e, 0xb2, 0x47,
	0x44, 0x72, 0xf0, 0xcb, 0xb5, 0xf3, 0x5b, 0x0d, 0xba, 0xf3, 0x21, 0x58, 0x1a, 0x46, 0x07, 0x1a,
	0x79, 0x1a, 0x50, 0x15, 0xcf, 0x9a, 0xa2, 0x35, 0x15, 0x89, 0x05, 0xb8, 0x9a, 0xf9, 0x23, 0x61,
	0x6a, 0x7a, 0x99, 0x98, 0xe1, 0x95, 0xe4, 0x58, 0xc8, 0x51, 0x3c, 0x34, 0xe1, 0x59, 0x22, 0xa9,
	0x79, 0xb6, 0x0b, 0x96, 0x97, 0xe3, 0x0a, 0x7d, 0x3d, 0x31, 0x21, 0x59, 0x14, 0x9e, 0x8a, 0x38,
	0x0f, 0xc1, 0x2a, 0x71, 0x65, 0x08, 0x75, 0x01, 0x63, 0x88, 0x5a, 0xab, 0xda, 0x39, 0xf7, 0xc2,
	0x5c, 0x98, 0x86, 0xa4, 0x37, 0xce, 0xb7, 0x5a, 0x4d, 0xe7, 0xd0, 0x03, 0x58, 0xa5, 0x7c, 0xcb,
	0x48, 0xd1, 0xee, 0xdf, 0x99, 0x4f, 0xb8, 0x7d, 0xf4, 0x52, 0x10, 0x79, 0x14, 0x09, 0x23, 0xaa,
	0x8a, 0xf7, 0x42, 0x04, 0x67, 0x23, 0x49, 0x07, 0x37, 0xb9, 0xd9, 0x39, 0xa7, 0xb0, 0xb5, 0x4c,
	0x4f, 0xdd, 0x2d, 0x89, 0x53, 0x49, 0x9f, 0x68, 0x72, 0x5a, 0x2b, 0x4c, 0x95, 0xb2, 0xb9, 0x1a,
	0xad, 0xa9, 0x29, 0xe4, 0x83, 0x4c, 0x48, 0xd3, 0x28, 0xcd, 0xce, 0xf1, 0xa1, 0x5d, 0x4d, 0x66,
	0xd6, 0xd5, 0x01, 0xd2, 0xa6, 0x52, 0x38, 0xee, 0x56, 0x5d, 0x67, 0xda, 0x6f, 0x09, 0xb0, 0x77,
	0xa1, 0x53, 0xd4, 0x88, 0xeb, 0xc7, 0x43, 0x1d, 0xb3, 0x26, 0x6f, 0x17, 0xe0, 0x1e, 0x62, 0xce,
	0x97, 0x60, 0x57, 0x12, 0xff, 0xbf, 0x7e, 0xc3, 0xc9, 0x8d, 0x57, 0x29, 0xcd, 0xdf, 0x83, 0x75,
	0x19, 0x4b, 0x2f, 0x54, 0xfd, 0x51, 0x8c, 0x13, 0x99, 0x19, 0xd3, 0x3b, 0x84, 0x3e, 0x36, 0x20,
	0x56, 0xcd, 0x46, 0x22, 0x52, 0x17, 0x35, 0xdc, 0xa2, 0xae, 0xea, 0x54, 0x57, 0x1d, 0x84, 0x4f,
	0xd2, 0xc9, 0x89, 0xa9, 0xae, 0xdb, 0xd0, 0xa2, 0xf2, 0x71, 0xb1, 0x5c, 0xb4, 0x67, 0xd6, 0x68,
	0xff, 0x22, 0x72, 0x7e, 0xaf, 0x01, 0x5b, 0xac, 0x19, 0xd5, 0xc1, 0x87, 0x22, 0xf4, 0x26, 0x6e,
	0x25, 0x27, 0x2c, 0x42, 0x68, 0x28, 0xdc, 0x03, 0x5b, 0xd3, 0xd3, 0xf4, 0x68, 0x72, 0xad, 0x71,
	0xaa, 0x10, 0xf6, 0x21, 0x74, 0x75, 0x9d, 0xe2, 0x45, 0x7c, 0x11, 0x49, 0xef, 0x4c, 0x3b, 0xad,
	0xce, 0x75, 0xfd, 0x1e, 0x95, 0x30, 0xfb, 0x08, 0x36, 0xbd, 0x01, 0x46, 0xd4, 0x15, 0x69, 0x1a,
	0xa7, 0xe6, 0x44, 0x3d, 0xd1, 0x36, 0x88, 0x78, 0xa2, 0xf0, 0xf2, 0x58, 0x2d, 0x5b, 0x39, 0xb6,
	0x59, 0x11, 0x9d, 0x1e, 0xeb, 0xfc, 0x51, 0x83, 0xf5, 0xd9, 0x62, 0x56, 0x73, 0xd1, 0x0b, 0xc3,
	0xf8, 0xc2, 0x45, 0x8f, 0x9f, 0x05, 0x91, 0x99, 0x08, 0x36, 0x61, 0x2f, 0x08, 0x52, 0x76, 0xe3,
	0xd6, 0x35, 0x05, 0xa7, 0x27, 0x83, 0x85, 0xc8, 0xa1, 0xae, 0x30, 0x4c, 0x04, 0x7d, 0xc2, 0x48,
	0x78, 0x43, 0x9c, 0xb6, 0xd4, 0x65, 0x2d, 0xae, 0x8f, 0x3d, 0xd0, 0x98, 0x0a, 0x9e, 0xb8, 0x4c,
	0xe2, 0x4c, 0x94, 0x52, 0x2b, 0x24, 0xd5, 0xd1, 0x68, 0x21, 0x76, 0x0b, 0xd6, 0xc6, 0xde, 0xa5,
	0x5b, 0x98, 0xd0, 0xc0, 0x32, 0xf6, 0x2e, 0x1f, 0xa3, 0x43, 0x3e, 0x46, 0x87, 0xd0, 0x47, 0x7c,
	0xcc, 0x2f, 0xb4, 0x26, 0xc0, 0x47, 0x07, 0xf5, 0xcb, 0x16, 0xef, 0x12, 0xb1, 0x37, 0xc5, 0x9d,
	0xef, 0xa1, 0x81, 0x93, 0x07, 0x4b, 0xbf, 0x49, 0xb3, 0x80, 0x6c, 0xb2, 0xfb, 0xbd, 0xe9, 0x50,
	0xa2, 0xea, 0x2e, 0xe7, 0x21, 0xd7, 0x62, 0xec, 0x83, 0xb2, 0x6c, 0xf5, 0x88, 0xd9, 0xa8, 0x4c,
	0x31, 0x1a, 0x13, 0x86, 0x76, 0x7e, 0xa9, 0xc1, 0xe6, 0xc2, 0x29, 0xec, 0x0e, 0x58, 0x59, 0x14,
	0xb8, 0xd5, 0xc1, 0xda, 0x42, 0xe0, 0x80, 0x66, 0xeb, 0x7d, 0xb8, 0x31, 0x9c, 0x16, 0xaf, 0x7a,
	0x5f, 0x44, 0x42, 0x16, 0x63, 0x96, 0x55, 0xa8, 0x63, 0xcd, 0x94, 0xe5, 0xdd, 0xa8, 0x94, 0x37,
	0x7a, 0x3a, 0x8b, 0xf3, 0x54, 0xbf, 0x4f, 0x50, 0xca, 0x64, 0x44, 0x5b, 0x83, 0x5a, 0x73, 0x66,
	0x8a, 0x37, 0x67, 0xa7, 0xb8, 0x33, 0x82, 0x56, 0x61, 0x0c, 0xdb, 0x87, 0x4d, 0x32, 0xc7, 0xad,
	0x7c, 0xdc, 0xf4, 0xab, 0x62, 0xb6, 0x2e, 0xf4, 0xaa, 0x6e, 0x3a, 0xdf, 0x85, 0xae, 0xea, 0x5a,
	0x1c, 0xba, 0xcb, 0x3a, 0x16, 0x75, 0xa7, 0xda, 0x42, 0x77, 0x52, 0xb6, 0xd4, 0xcb, 0xee, 0xa4,
	0xac, 0x58, 0x62, 0xbe, 0xf3, 0x1d, 0x86, 0xd5, 0x4f, 0xd8, 0x27, 0xb3, 0x61, 0xbd, 0x39, 0x7d,
	0x4d, 0xcc, 0xbc, 0x03, 0x4c, 0x50, 0x77, 0xe6, 0x82, 0xda, 0xad, 0x3c, 0x3e, 0x08, 0x2f, 0xa3,
	0xfa, 0x73, 0x1d, 0x36, 0xe6, 0x0e, 0xb9, 0x2a, 0x6c, 0xb5, 0x7f, 0x0c, 0x5b, 0xfd, 0x75, 0x61,
	0x6b, 0x2c, 0x09, 0xdb, 0x21, 0x74, 0x8e, 0xb5, 0x50, 0xe8, 0x0d, 0x44, 0xf9, 0x92, 0xda, 0x59,
	0x6e, 0xdd, 0xae, 0x96, 0xfd, 0x86, 0x44, 0x9f, 0x44, 0xea, 0x31, 0xd0, 0xae, 0x42, 0xaf, 0xcb,
	0x82, 0xed, 0xaf, 0x60, 0x73, 0x41, 0x5d, 0xb5, 0xe6, 0x57, 0x62, 0x52, 0xb4, 0x66, 0x5c, 0x2e,
	0x1f, 0x74, 0x9f, 0xd7, 0x1f, 0xd5, 0x1c, 0xec, 0x74, 0x95, 0x03, 0x16, 0x55, 0xb1, 0x00, 0xad,
	0xd2, 0xbf, 0xec, 0x33, 0xd5, 0x17, 0xff, 0x75, 0x8a, 0x55, 0x65, 0xaf, 0xca, 0xae, 0xfe, 0x9f,
	0x75, 0x58, 0x33, 0xff, 0x25, 0xd8, 0x33, 0xd8, 0xc2, 0xda, 0x47, 0xdb, 0xe6, 0xfe, 0x5c, 0x14,
	0x8f, 0x97, 0x59, 0x78, 0xbb, 0x48, 0x17, 0xb3, 0xe7, 0xf8, 0x66, 0x8f, 0xa3, 0x4c, 0x38, 0x6f,
	0xa8, 0x82, 0x78, 0x26, 0xe4, 0x75, 0x4f, 0xc1, 0xeb, 0xec, 0x8b, 0x50, 0x5c, 0xff, 0x3a, 0x4f,
	0xe1, 0xc6, 0x91, 0x8a, 0xf8, 0xff, 0x60, 0xd6, 0x51, 0x7e, 0x5d, 0xb3, 0x06, 0xab, 0x44, 0x3c,
	0xf8, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xff, 0xec, 0x3c, 0xb5, 0xf2, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualClient is the client API for Virtual service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualClient interface {
	CreateVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error)
	GetVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error)
	DeleteVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error)
	PatchVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error)
	PutVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type virtualClient struct {
	cc *grpc.ClientConn
}

func NewVirtualClient(cc *grpc.ClientConn) VirtualClient {
	return &virtualClient{cc}
}

func (c *virtualClient) CreateVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.Virtual/CreateVirtualService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualClient) GetVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.Virtual/GetVirtualService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualClient) DeleteVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.Virtual/DeleteVirtualService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualClient) PatchVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.Virtual/PatchVirtualService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualClient) PutVirtualService(ctx context.Context, in *VirtualService, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/proto.Virtual/PutVirtualService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualServer is the server API for Virtual service.
type VirtualServer interface {
	CreateVirtualService(context.Context, *VirtualService) (*ServiceResponse, error)
	GetVirtualService(context.Context, *VirtualService) (*ServiceResponse, error)
	DeleteVirtualService(context.Context, *VirtualService) (*ServiceResponse, error)
	PatchVirtualService(context.Context, *VirtualService) (*ServiceResponse, error)
	PutVirtualService(context.Context, *VirtualService) (*ServiceResponse, error)
}

// UnimplementedVirtualServer can be embedded to have forward compatible implementations.
type UnimplementedVirtualServer struct {
}

func (*UnimplementedVirtualServer) CreateVirtualService(ctx context.Context, req *VirtualService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVirtualService not implemented")
}
func (*UnimplementedVirtualServer) GetVirtualService(ctx context.Context, req *VirtualService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualService not implemented")
}
func (*UnimplementedVirtualServer) DeleteVirtualService(ctx context.Context, req *VirtualService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVirtualService not implemented")
}
func (*UnimplementedVirtualServer) PatchVirtualService(ctx context.Context, req *VirtualService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchVirtualService not implemented")
}
func (*UnimplementedVirtualServer) PutVirtualService(ctx context.Context, req *VirtualService) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutVirtualService not implemented")
}

func RegisterVirtualServer(s *grpc.Server, srv VirtualServer) {
	s.RegisterService(&_Virtual_serviceDesc, srv)
}

func _Virtual_CreateVirtualService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualServer).CreateVirtualService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Virtual/CreateVirtualService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualServer).CreateVirtualService(ctx, req.(*VirtualService))
	}
	return interceptor(ctx, in, info, handler)
}

func _Virtual_GetVirtualService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualServer).GetVirtualService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Virtual/GetVirtualService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualServer).GetVirtualService(ctx, req.(*VirtualService))
	}
	return interceptor(ctx, in, info, handler)
}

func _Virtual_DeleteVirtualService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualServer).DeleteVirtualService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Virtual/DeleteVirtualService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualServer).DeleteVirtualService(ctx, req.(*VirtualService))
	}
	return interceptor(ctx, in, info, handler)
}

func _Virtual_PatchVirtualService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualServer).PatchVirtualService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Virtual/PatchVirtualService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualServer).PatchVirtualService(ctx, req.(*VirtualService))
	}
	return interceptor(ctx, in, info, handler)
}

func _Virtual_PutVirtualService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualServer).PutVirtualService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Virtual/PutVirtualService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualServer).PutVirtualService(ctx, req.(*VirtualService))
	}
	return interceptor(ctx, in, info, handler)
}

var _Virtual_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Virtual",
	HandlerType: (*VirtualServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVirtualService",
			Handler:    _Virtual_CreateVirtualService_Handler,
		},
		{
			MethodName: "GetVirtualService",
			Handler:    _Virtual_GetVirtualService_Handler,
		},
		{
			MethodName: "DeleteVirtualService",
			Handler:    _Virtual_DeleteVirtualService_Handler,
		},
		{
			MethodName: "PatchVirtualService",
			Handler:    _Virtual_PatchVirtualService_Handler,
		},
		{
			MethodName: "PutVirtualService",
			Handler:    _Virtual_PutVirtualService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "virtualservice.proto",
}
